# (PART\*) Get Started {-}

# Introduzione {-}

In questa sezione verranno prima presentate le istruzioni per installare R ed RStudio. Successivamente, svolgeremo le prime operazioni in R e familiarizzeremo con dei concetti di base della programmazione quali gli oggetti e le funzioni. Introdurremmo infine altri concetti relativi alle sessioni di lavoro in R e descriveremo alcune buone regole per l'utilizzo di R.

I capitoli sono così organizzati:

- **Capitolo \@ref(install) - Installare R e RStudio**. Istruzioni passo passo per installare R e RStudio.
- **Capitolo \@ref(rstudio-gui) - Interfaccia RStudio**. Introduzione all'interfaccia utente di RStudio.
- **Capitolo \@ref(first-commands) - Primi Passi in R**. Operatori matematici, operatori relazionali, operatori logici.
- **Capitolo \@ref(objects-functions) - Due Compagni Inseparabili**. Introduzione dei concetti di oggetti e funzioni in R.
- **Capitolo \@ref(working-environment) - Ambiente di Lavoro**. Introduzione dei concetti di Environment, working directory e dei pacchetti di R.
- **Capitolo \@ref(working-session) - Sessione di Lavoro**. Descrizione di buone pratiche nelle sessioni di lavoro e gestione degli errori.
