# (PART\*) Strutture Dati {-}

# Introduzione {#second-section -}

In questa sezione verranno introdotte le principali tipologie di oggetti usati in R . Ovvero le principali strutture in cui possono essere organizzati i dati: vettori, matrici, dataframe e liste.

Per ognuna di esse descriveremo le loro caratteristiche e vedremo come crearle, modificarle e manipolarle a seconda delle necessità

I capitoli sono così organizzati:

- **Capitolo \@ref(vector) - Vettori**. Impareremo le caratteristiche e l'uso dei vettori soffermandoci anche sulle diverse tipologie di dati.
- **Capitolo \@ref(factor) - Fattori**. Impareremo le caratteristiche e l'uso dei fattori, ovvero un particolare tipo di vettori usati per le variabili categoriali ed ordinali.
- **Capitolo \@ref(matrix) - Matrici**. Impareremo le caratteristiche e l'uso delle matrici introducendo anche gli array.
- **Capitolo \@ref(dataframe) - Dataframe**. Impareremo le caratteristiche e l'uso dei dataframe, l'oggetto maggiormente utilizzato nell'analisi di dati.
- **Capitolo \@ref(list) - Liste**. Impareremo le caratteristiche e l'uso delle liste.
