<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capitolo 10 Dataframe | Introduction to R</title>
  <meta name="description" content="Questo è un libro intorduttivo ad R prodotto da Psicostat, gruppo di ricerca interdisciplinare che unisce la passione per la statistica e la psicologia." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Capitolo 10 Dataframe | Introduction to R" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://psicostat.github.io/Introduction2R/" />
  <meta property="og:image" content="https://psicostat.github.io/Introduction2R/images/logo_psicostat.png" />
  <meta property="og:description" content="Questo è un libro intorduttivo ad R prodotto da Psicostat, gruppo di ricerca interdisciplinare che unisce la passione per la statistica e la psicologia." />
  <meta name="github-repo" content="psicostat/Introduction2R" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capitolo 10 Dataframe | Introduction to R" />
  
  <meta name="twitter:description" content="Questo è un libro intorduttivo ad R prodotto da Psicostat, gruppo di ricerca interdisciplinare che unisce la passione per la statistica e la psicologia." />
  <meta name="twitter:image" content="https://psicostat.github.io/Introduction2R/images/logo_psicostat.png" />

<meta name="author" content="Claudio Zandonella Callegher and Filippo Gambarota members of Psicostat" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="matrix.html"/>
<link rel="next" href="list.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-RM7HE6D2VW"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-RM7HE6D2VW');
</script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="assets/style.css" type="text/css" />
<link rel="stylesheet" href="assets/toc.css" type="text/css" />
<link rel="stylesheet" href="assets/custom.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="toc-logo"><a href="./"><img src="images/hex_psicostat.png"></a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Presentazione</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#perchè-r"><i class="fa fa-check"></i>Perchè R</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#struttura-del-libro"><i class="fa fa-check"></i>Struttura del libro</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#risorse-utili"><i class="fa fa-check"></i>Risorse Utili</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#psicostat"><i class="fa fa-check"></i>Psicostat</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#collaborazione"><i class="fa fa-check"></i>Collaborazione</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#riconoscimenti"><i class="fa fa-check"></i>Riconoscimenti</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#licenza"><i class="fa fa-check"></i>Licenza</a></li>
</ul></li>
<li class="part"><span><b>Get Started</b></span></li>
<li class="chapter" data-level="" data-path="introduzione.html"><a href="introduzione.html"><i class="fa fa-check"></i>Introduzione</a></li>
<li class="chapter" data-level="1" data-path="install.html"><a href="install.html"><i class="fa fa-check"></i><b>1</b> Installare R e RStudio</a><ul>
<li class="chapter" data-level="1.1" data-path="install.html"><a href="install.html#install-r"><i class="fa fa-check"></i><b>1.1</b> Installare R</a><ul>
<li class="chapter" data-level="1.1.1" data-path="install.html"><a href="install.html#r-windows"><i class="fa fa-check"></i><b>1.1.1</b> R Windows</a></li>
<li class="chapter" data-level="1.1.2" data-path="install.html"><a href="install.html#r-macos"><i class="fa fa-check"></i><b>1.1.2</b> R MacOS</a></li>
<li class="chapter" data-level="1.1.3" data-path="install.html"><a href="install.html#r-linux"><i class="fa fa-check"></i><b>1.1.3</b> R Linux</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="install.html"><a href="install.html#installare-r-studio"><i class="fa fa-check"></i><b>1.2</b> Installare R Studio</a><ul>
<li class="chapter" data-level="1.2.1" data-path="install.html"><a href="install.html#r-studio-in-linux"><i class="fa fa-check"></i><b>1.2.1</b> R Studio in Linux</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="rstudio-gui.html"><a href="rstudio-gui.html"><i class="fa fa-check"></i><b>2</b> Interfaccia RStudio</a></li>
<li class="chapter" data-level="3" data-path="first-comands.html"><a href="first-comands.html"><i class="fa fa-check"></i><b>3</b> Primi Passi in R</a><ul>
<li class="chapter" data-level="3.1" data-path="first-comands.html"><a href="first-comands.html#math-operators"><i class="fa fa-check"></i><b>3.1</b> Operatori Matematici</a><ul>
<li class="chapter" data-level="3.1.1" data-path="first-comands.html"><a href="first-comands.html#ordine-operazioni"><i class="fa fa-check"></i><b>3.1.1</b> Ordine Operazioni</a></li>
<li class="chapter" data-level="" data-path="first-comands.html"><a href="first-comands.html#esercizi"><i class="fa fa-check"></i>Esercizi</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="first-comands.html"><a href="first-comands.html#operators-rel-log"><i class="fa fa-check"></i><b>3.2</b> Operatori Relazionali e Logici</a><ul>
<li class="chapter" data-level="3.2.1" data-path="first-comands.html"><a href="first-comands.html#operatori-relazionali"><i class="fa fa-check"></i><b>3.2.1</b> Operatori Relazionali</a></li>
<li class="chapter" data-level="3.2.2" data-path="first-comands.html"><a href="first-comands.html#operatori-logici"><i class="fa fa-check"></i><b>3.2.2</b> Operatori Logici</a></li>
<li class="chapter" data-level="3.2.3" data-path="first-comands.html"><a href="first-comands.html#ordine-valutazione-relazioni"><i class="fa fa-check"></i><b>3.2.3</b> Ordine valutazione relazioni</a></li>
<li class="chapter" data-level="" data-path="first-comands.html"><a href="first-comands.html#esercizi-1"><i class="fa fa-check"></i>Esercizi</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="objects-functions.html"><a href="objects-functions.html"><i class="fa fa-check"></i><b>4</b> Due Compagni Inseparabili</a><ul>
<li class="chapter" data-level="4.1" data-path="objects-functions.html"><a href="objects-functions.html#objects-section"><i class="fa fa-check"></i><b>4.1</b> Oggetti</a><ul>
<li class="chapter" data-level="4.1.1" data-path="objects-functions.html"><a href="objects-functions.html#assign"><i class="fa fa-check"></i><b>4.1.1</b> Assegnare e Richiamare un oggetto</a></li>
<li class="chapter" data-level="4.1.2" data-path="objects-functions.html"><a href="objects-functions.html#objects-names"><i class="fa fa-check"></i><b>4.1.2</b> Nomi degli oggetti</a></li>
<li class="chapter" data-level="4.1.3" data-path="objects-functions.html"><a href="objects-functions.html#tipologie-dati-e-strutture-dati"><i class="fa fa-check"></i><b>4.1.3</b> Tipologie Dati e Strutture Dati</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="objects-functions.html"><a href="objects-functions.html#functions-def"><i class="fa fa-check"></i><b>4.2</b> Funzioni</a><ul>
<li class="chapter" data-level="4.2.1" data-path="objects-functions.html"><a href="objects-functions.html#function-arguments"><i class="fa fa-check"></i><b>4.2.1</b> Argomenti di una Funzione</a></li>
<li class="chapter" data-level="4.2.2" data-path="objects-functions.html"><a href="objects-functions.html#help"><i class="fa fa-check"></i><b>4.2.2</b> Help! I need Somebody…Help!</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="working-environment.html"><a href="working-environment.html"><i class="fa fa-check"></i><b>5</b> Ambiente di Lavoro</a><ul>
<li class="chapter" data-level="5.1" data-path="working-environment.html"><a href="working-environment.html#environment"><i class="fa fa-check"></i><b>5.1</b> Environment</a><ul>
<li class="chapter" data-level="5.1.1" data-path="working-environment.html"><a href="working-environment.html#aggiungere-oggetti-allenvironment"><i class="fa fa-check"></i><b>5.1.1</b> Aggiungere Oggetti all’Environment</a></li>
<li class="chapter" data-level="5.1.2" data-path="working-environment.html"><a href="working-environment.html#rimuovere-oggetti-dallenvironment"><i class="fa fa-check"></i><b>5.1.2</b> Rimuovere Oggetti dall’Environment</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="working-environment.html"><a href="working-environment.html#working-directory"><i class="fa fa-check"></i><b>5.2</b> Working Directory</a><ul>
<li class="chapter" data-level="5.2.1" data-path="working-environment.html"><a href="working-environment.html#organizzazione-computer"><i class="fa fa-check"></i><b>5.2.1</b> Organizzazione Computer</a></li>
<li class="chapter" data-level="5.2.2" data-path="working-environment.html"><a href="working-environment.html#absolute-path-e-relative-path"><i class="fa fa-check"></i><b>5.2.2</b> Absolute Path e Relative Path</a></li>
<li class="chapter" data-level="5.2.3" data-path="working-environment.html"><a href="working-environment.html#working-directory-in-r"><i class="fa fa-check"></i><b>5.2.3</b> Working Directory in R</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="working-environment.html"><a href="working-environment.html#packages"><i class="fa fa-check"></i><b>5.3</b> R-packages</a><ul>
<li class="chapter" data-level="5.3.1" data-path="working-environment.html"><a href="working-environment.html#install.packages"><i class="fa fa-check"></i><b>5.3.1</b> install.packages()</a></li>
<li class="chapter" data-level="5.3.2" data-path="working-environment.html"><a href="working-environment.html#library"><i class="fa fa-check"></i><b>5.3.2</b> library()</a></li>
<li class="chapter" data-level="5.3.3" data-path="working-environment.html"><a href="working-environment.html#aggiornare-e-rimuovere-pacchetti"><i class="fa fa-check"></i><b>5.3.3</b> Aggiornare e Rimuovere Pacchetti</a></li>
<li class="chapter" data-level="5.3.4" data-path="working-environment.html"><a href="working-environment.html#documentazione-pacchetti"><i class="fa fa-check"></i><b>5.3.4</b> Documentazione Pacchetti</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="working-session.html"><a href="working-session.html"><i class="fa fa-check"></i><b>6</b> Sessione di Lavoro</a><ul>
<li class="chapter" data-level="6.1" data-path="working-session.html"><a href="working-session.html#organizzazione-script"><i class="fa fa-check"></i><b>6.1</b> Organizzazione Script</a><ul>
<li class="chapter" data-level="6.1.1" data-path="working-session.html"><a href="working-session.html#creare-delle-sezioni"><i class="fa fa-check"></i><b>6.1.1</b> Creare delle Sezioni</a></li>
<li class="chapter" data-level="6.1.2" data-path="working-session.html"><a href="working-session.html#sintax"><i class="fa fa-check"></i><b>6.1.2</b> Sintassi</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="working-session.html"><a href="working-session.html#organizzazione-progetti"><i class="fa fa-check"></i><b>6.2</b> Organizzazione Progetti</a><ul>
<li class="chapter" data-level="6.2.1" data-path="working-session.html"><a href="working-session.html#rstudio-projects"><i class="fa fa-check"></i><b>6.2.1</b> RStudio Projects</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="working-session.html"><a href="working-session.html#messages-warnings-e-errors"><i class="fa fa-check"></i><b>6.3</b> Messages, Warnings e Errors</a><ul>
<li class="chapter" data-level="6.3.1" data-path="working-session.html"><a href="working-session.html#risolvere-gli-errori"><i class="fa fa-check"></i><b>6.3.1</b> Risolvere gli Errori</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>Struttura Dati</b></span></li>
<li class="chapter" data-level="" data-path="second-section.html"><a href="second-section.html"><i class="fa fa-check"></i>Introduzione</a></li>
<li class="chapter" data-level="7" data-path="vector.html"><a href="vector.html"><i class="fa fa-check"></i><b>7</b> Vettori</a><ul>
<li class="chapter" data-level="7.1" data-path="vector.html"><a href="vector.html#creazione"><i class="fa fa-check"></i><b>7.1</b> Creazione</a><ul>
<li class="chapter" data-level="" data-path="vector.html"><a href="vector.html#esercizi-2"><i class="fa fa-check"></i>Esercizi</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="vector.html"><a href="vector.html#vector-selection"><i class="fa fa-check"></i><b>7.2</b> Selezione Elementi</a><ul>
<li class="chapter" data-level="7.2.1" data-path="vector.html"><a href="vector.html#vector-selection-advanced"><i class="fa fa-check"></i><b>7.2.1</b> Utilizzi Avanzati Selezione</a></li>
<li class="chapter" data-level="" data-path="vector.html"><a href="vector.html#esercizi-3"><i class="fa fa-check"></i>Esercizi</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="vector.html"><a href="vector.html#vector-functions"><i class="fa fa-check"></i><b>7.3</b> Funzioni ed Operazioni</a><ul>
<li class="chapter" data-level="" data-path="vector.html"><a href="vector.html#esercizi-4"><i class="fa fa-check"></i>Esercizi</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="vector.html"><a href="vector.html#data-type"><i class="fa fa-check"></i><b>7.4</b> Data Type</a><ul>
<li class="chapter" data-level="7.4.1" data-path="vector.html"><a href="vector.html#character"><i class="fa fa-check"></i><b>7.4.1</b> Character</a></li>
<li class="chapter" data-level="7.4.2" data-path="vector.html"><a href="vector.html#numeric"><i class="fa fa-check"></i><b>7.4.2</b> Numeric</a></li>
<li class="chapter" data-level="7.4.3" data-path="vector.html"><a href="vector.html#integer"><i class="fa fa-check"></i><b>7.4.3</b> Integer</a></li>
<li class="chapter" data-level="7.4.4" data-path="vector.html"><a href="vector.html#logical-vector"><i class="fa fa-check"></i><b>7.4.4</b> Logical</a></li>
<li class="chapter" data-level="7.4.5" data-path="vector.html"><a href="vector.html#valori-speciali"><i class="fa fa-check"></i><b>7.4.5</b> Valori speciali</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="factor.html"><a href="factor.html"><i class="fa fa-check"></i><b>8</b> Fattori</a><ul>
<li class="chapter" data-level="8.1" data-path="factor.html"><a href="factor.html#attributes"><i class="fa fa-check"></i><b>8.1</b> Attributi di un Oggetto</a><ul>
<li class="chapter" data-level="8.1.1" data-path="factor.html"><a href="factor.html#attributi-di-un-vettore"><i class="fa fa-check"></i><b>8.1.1</b> Attributi di un Vettore</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="factor.html"><a href="factor.html#fattori"><i class="fa fa-check"></i><b>8.2</b> Fattori</a><ul>
<li class="chapter" data-level="8.2.1" data-path="factor.html"><a href="factor.html#funzionamento-fatori"><i class="fa fa-check"></i><b>8.2.1</b> Funzionamento Fatori</a></li>
<li class="chapter" data-level="8.2.2" data-path="factor.html"><a href="factor.html#operazioni-fattori"><i class="fa fa-check"></i><b>8.2.2</b> Operazioni Fattori</a></li>
<li class="chapter" data-level="8.2.3" data-path="factor.html"><a href="factor.html#fattori-ordinali"><i class="fa fa-check"></i><b>8.2.3</b> Fattori Ordinali</a></li>
<li class="chapter" data-level="" data-path="factor.html"><a href="factor.html#esercizi-5"><i class="fa fa-check"></i>Esercizi</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="matrix.html"><a href="matrix.html"><i class="fa fa-check"></i><b>9</b> Matrici</a><ul>
<li class="chapter" data-level="9.1" data-path="matrix.html"><a href="matrix.html#creazione-1"><i class="fa fa-check"></i><b>9.1</b> Creazione</a><ul>
<li class="chapter" data-level="9.1.1" data-path="matrix.html"><a href="matrix.html#matrix-types"><i class="fa fa-check"></i><b>9.1.1</b> Tipologie di Matrici</a></li>
<li class="chapter" data-level="" data-path="matrix.html"><a href="matrix.html#esercizi-6"><i class="fa fa-check"></i>Esercizi</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="matrix.html"><a href="matrix.html#sel-matrix"><i class="fa fa-check"></i><b>9.2</b> Selezione Elementi</a><ul>
<li class="chapter" data-level="9.2.1" data-path="matrix.html"><a href="matrix.html#matrix-selection-advanced"><i class="fa fa-check"></i><b>9.2.1</b> Utilizzi Avanzati Selezione</a></li>
<li class="chapter" data-level="" data-path="matrix.html"><a href="matrix.html#esercizi-7"><i class="fa fa-check"></i>Esercizi</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="matrix.html"><a href="matrix.html#funzioni-ed-operazioni"><i class="fa fa-check"></i><b>9.3</b> Funzioni ed Operazioni</a><ul>
<li class="chapter" data-level="9.3.1" data-path="matrix.html"><a href="matrix.html#mat-prop"><i class="fa fa-check"></i><b>9.3.1</b> Attributi di una Matrice</a></li>
<li class="chapter" data-level="9.3.2" data-path="matrix.html"><a href="matrix.html#matrix-bind"><i class="fa fa-check"></i><b>9.3.2</b> Unire Matrici</a></li>
<li class="chapter" data-level="9.3.3" data-path="matrix.html"><a href="matrix.html#operatori-matematici"><i class="fa fa-check"></i><b>9.3.3</b> Operatori Matematici</a></li>
<li class="chapter" data-level="" data-path="matrix.html"><a href="matrix.html#esercizi-8"><i class="fa fa-check"></i>Esercizi</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="matrix.html"><a href="matrix.html#array"><i class="fa fa-check"></i><b>9.4</b> Array</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="dataframe.html"><a href="dataframe.html"><i class="fa fa-check"></i><b>10</b> Dataframe</a><ul>
<li class="chapter" data-level="10.1" data-path="dataframe.html"><a href="dataframe.html#creazione-di-un-dataframe"><i class="fa fa-check"></i><b>10.1</b> Creazione di un dataframe</a><ul>
<li class="chapter" data-level="" data-path="dataframe.html"><a href="dataframe.html#esercizi-9"><i class="fa fa-check"></i>Esercizi</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="dataframe.html"><a href="dataframe.html#sel-df"><i class="fa fa-check"></i><b>10.2</b> Selezione Elementi</a><ul>
<li class="chapter" data-level="10.2.1" data-path="dataframe.html"><a href="dataframe.html#utilizzi-avanzati-selezione"><i class="fa fa-check"></i><b>10.2.1</b> Utilizzi Avanzati Selezione</a></li>
<li class="chapter" data-level="" data-path="dataframe.html"><a href="dataframe.html#esercizi-10"><i class="fa fa-check"></i>Esercizi</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="dataframe.html"><a href="dataframe.html#funzioni-ed-operazioni-1"><i class="fa fa-check"></i><b>10.3</b> Funzioni ed Operazioni</a><ul>
<li class="chapter" data-level="10.3.1" data-path="dataframe.html"><a href="dataframe.html#attributi-di-un-dataframe"><i class="fa fa-check"></i><b>10.3.1</b> Attributi di un Dataframe</a></li>
<li class="chapter" data-level="10.3.2" data-path="dataframe.html"><a href="dataframe.html#unire-dataframe"><i class="fa fa-check"></i><b>10.3.2</b> Unire Dataframe</a></li>
<li class="chapter" data-level="10.3.3" data-path="dataframe.html"><a href="dataframe.html#informazioni-dataframe"><i class="fa fa-check"></i><b>10.3.3</b> Informazioni Dataframe</a></li>
<li class="chapter" data-level="" data-path="dataframe.html"><a href="dataframe.html#esercizi-11"><i class="fa fa-check"></i>Esercizi</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="list.html"><a href="list.html"><i class="fa fa-check"></i><b>11</b> Liste</a><ul>
<li class="chapter" data-level="11.1" data-path="list.html"><a href="list.html#creazione-di-liste"><i class="fa fa-check"></i><b>11.1</b> Creazione di Liste</a><ul>
<li class="chapter" data-level="" data-path="list.html"><a href="list.html#esercizi-12"><i class="fa fa-check"></i>Esercizi</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="list.html"><a href="list.html#selezione-elementi"><i class="fa fa-check"></i><b>11.2</b> Selezione Elementi</a><ul>
<li class="chapter" data-level="11.2.1" data-path="list.html"><a href="list.html#utilizzi-avanzati-selezione-1"><i class="fa fa-check"></i><b>11.2.1</b> Utilizzi Avanzati Selezione</a></li>
<li class="chapter" data-level="" data-path="list.html"><a href="list.html#esercizi-13"><i class="fa fa-check"></i>Esercizi</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="list.html"><a href="list.html#funzioni-ed-operazioni-2"><i class="fa fa-check"></i><b>11.3</b> Funzioni ed Operazioni</a><ul>
<li class="chapter" data-level="11.3.1" data-path="list.html"><a href="list.html#attributi-di-una-lista"><i class="fa fa-check"></i><b>11.3.1</b> Attributi di una Lista</a></li>
<li class="chapter" data-level="11.3.2" data-path="list.html"><a href="list.html#unire-liste"><i class="fa fa-check"></i><b>11.3.2</b> Unire Liste</a></li>
<li class="chapter" data-level="11.3.3" data-path="list.html"><a href="list.html#informazioni-lista"><i class="fa fa-check"></i><b>11.3.3</b> Informazioni Lista</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="list.html"><a href="list.html#struttura-nested"><i class="fa fa-check"></i><b>11.4</b> Struttura Nested</a></li>
</ul></li>
<li class="part"><span><b>Algoritmi</b></span></li>
<li class="chapter" data-level="" data-path="third-section.html"><a href="third-section.html"><i class="fa fa-check"></i>Introduzione</a></li>
<li class="chapter" data-level="12" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>12</b> Definizione di Funzioni</a><ul>
<li class="chapter" data-level="12.1" data-path="functions.html"><a href="functions.html#creazione-di-una-funzione"><i class="fa fa-check"></i><b>12.1</b> Creazione di una Funzione</a><ul>
<li class="chapter" data-level="12.1.1" data-path="functions.html"><a href="functions.html#definire-input-e-output"><i class="fa fa-check"></i><b>12.1.1</b> Definire Input e Output</a></li>
<li class="chapter" data-level="" data-path="functions.html"><a href="functions.html#esercizi-14"><i class="fa fa-check"></i>Esercizi</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="functions.html"><a href="functions.html#lavorare-con-le-funzioni"><i class="fa fa-check"></i><b>12.2</b> Lavorare con le Funzioni</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="coditionals.html"><a href="coditionals.html"><i class="fa fa-check"></i><b>13</b> Programmazione Condizionale</a><ul>
<li class="chapter" data-level="13.1" data-path="coditionals.html"><a href="coditionals.html#strutture-condizionali"><i class="fa fa-check"></i><b>13.1</b> Strutture condizionali</a><ul>
<li class="chapter" data-level="13.1.1" data-path="coditionals.html"><a href="coditionals.html#if"><i class="fa fa-check"></i><b>13.1.1</b> if</a></li>
<li class="chapter" data-level="13.1.2" data-path="coditionals.html"><a href="coditionals.html#ifelse"><i class="fa fa-check"></i><b>13.1.2</b> if…else</a></li>
<li class="chapter" data-level="13.1.3" data-path="coditionals.html"><a href="coditionals.html#nested"><i class="fa fa-check"></i><b>13.1.3</b> Nested</a></li>
<li class="chapter" data-level="" data-path="coditionals.html"><a href="coditionals.html#esercizi-15"><i class="fa fa-check"></i>Esercizi</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="coditionals.html"><a href="coditionals.html#altri-operatori-condizinali"><i class="fa fa-check"></i><b>13.2</b> Altri Operatori Condizinali</a><ul>
<li class="chapter" data-level="13.2.1" data-path="coditionals.html"><a href="coditionals.html#switch"><i class="fa fa-check"></i><b>13.2.1</b> switch</a></li>
<li class="chapter" data-level="13.2.2" data-path="coditionals.html"><a href="coditionals.html#ifelse-1"><i class="fa fa-check"></i><b>13.2.2</b> ifelse</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="loop.html"><a href="loop.html"><i class="fa fa-check"></i><b>14</b> Programmazione Iterativa</a><ul>
<li class="chapter" data-level="14.1" data-path="loop.html"><a href="loop.html#loop-1"><i class="fa fa-check"></i><b>14.1</b> Loop</a><ul>
<li class="chapter" data-level="14.1.1" data-path="loop.html"><a href="loop.html#for"><i class="fa fa-check"></i><b>14.1.1</b> For</a></li>
<li class="chapter" data-level="14.1.2" data-path="loop.html"><a href="loop.html#while"><i class="fa fa-check"></i><b>14.1.2</b> While</a></li>
<li class="chapter" data-level="14.1.3" data-path="loop.html"><a href="loop.html#next-e-brake"><i class="fa fa-check"></i><b>14.1.3</b> Next e Brake</a></li>
<li class="chapter" data-level="" data-path="loop.html"><a href="loop.html#esercizi-16"><i class="fa fa-check"></i>Esercizi</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="loop.html"><a href="loop.html#apply-family"><i class="fa fa-check"></i><b>14.2</b> Apply Family</a><ul>
<li class="chapter" data-level="14.2.1" data-path="loop.html"><a href="loop.html#apply"><i class="fa fa-check"></i><b>14.2.1</b> apply</a></li>
<li class="chapter" data-level="14.2.2" data-path="loop.html"><a href="loop.html#tapply"><i class="fa fa-check"></i><b>14.2.2</b> tapply</a></li>
<li class="chapter" data-level="14.2.3" data-path="loop.html"><a href="loop.html#lapply"><i class="fa fa-check"></i><b>14.2.3</b> lapply</a></li>
<li class="chapter" data-level="14.2.4" data-path="loop.html"><a href="loop.html#sapply"><i class="fa fa-check"></i><b>14.2.4</b> sapply</a></li>
<li class="chapter" data-level="14.2.5" data-path="loop.html"><a href="loop.html#vapply"><i class="fa fa-check"></i><b>14.2.5</b> vapply</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="loop.html"><a href="loop.html#replicate"><i class="fa fa-check"></i><b>14.3</b> Replicate</a></li>
</ul></li>
<li class="part"><span><b>Case study</b></span></li>
<li class="chapter" data-level="" data-path="introduzione-1.html"><a href="introduzione-1.html"><i class="fa fa-check"></i>Introduzione</a></li>
<li class="chapter" data-level="15" data-path="attachment.html"><a href="attachment.html"><i class="fa fa-check"></i><b>15</b> Caso Studio I: Attaccamento</a><ul>
<li class="chapter" data-level="15.1" data-path="attachment.html"><a href="attachment.html#infobox"><i class="fa fa-check"></i><b>15.1</b> Infobox</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"><span style="font-size: 2.5em">Introduction to R</span></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<head>
  <meta name="viewport" content="width=device-width,minimum-scale=1.0,maximum-scale=10.0,initial-scale=1.0">
  <!--script src="https://kit.fontawesome.com/6a26f47516.js"></script-->
  <script src="assets/hideOutput.js"></script>
  <link href="assets/style.css" rel="stylesheet">
</head>



<div class="hero-image-container">
  <img class= "hero-image" src="images/banner.png">
</div>
<div id="dataframe" class="section level1">
<h1><span class="header-section-number">Capitolo 10</span> Dataframe</h1>
<p>I <code>dataframe</code> sono uno degli oggetti più utilizzati in R per rappresentare i propri dati. In modo analogo alle matrici, i <code>dataframe</code> sono una struttura <strong>bidimensionale</strong> dove i dati sono disposti secondo righe e colonne. Può essere utile pensare al dataframe esattamente come ad una normale tabella che si può creare in un foglio di calcolo (e.g., Excel) dove possiamo inserire i nostri dati. Dati in questo caso è volutamente generico poichè i dataframe, a differenza delle matrici, possono contenere nello stesso oggetto tipi diversi di dati (e.g., <em>nomi</em>, <em>date</em> e <em>numeri</em>).</p>
<p>La struttura di base di un dataframe è quindi la stessa di una matrice ma ci permette di includere diversi tipi di dati nello stesso oggetto come caratteri e valori numerici. Questo ci consente di raccogliere in un unico oggetto tutte le caratteristiche delle unità statistiche (variabili numeriche, categoriali, nominali etc.) che intendiamo successivamente analizzare. Un aspetto cruciale quindi è proprio quello che il dataframe è stato pensato per gestire dati complessi ed eterogenei come quelli che si trovano in un’analisi di dati reale. Se vi capiterà di utilizzare altri linguaggi di programmazione sopratutto mirati all’analisi dati (e.g., Matlab) noterete come vi mancherà un oggetto potente e intuitivo come il dataframe.</p>
<p>In genere in un dataframe le righe rappresentano le unità statitiche (ad esempio persone o osservazioni) e le colonne rappresentano variabili ovvero delle proprietà misurate su quelle unità statistiche. Esistono tuttavia due formati principali di dataframe a seconda del modo in cui vengono organizzati i dati. Abbiamo i dataframe in forma <strong>wide</strong> (oppure larga) oppure i dataframe in forma <strong>long</strong> (oppure lunga). Valutiamo la differenza tra i due formati ipotizzando dei dati dove per ogni soggetto abbiamo misuriamo l’età, il genere, e la risposta a tre item di un questionario.</p>
<div id="wide-dataframe" class="section level4 unnumbered">
<h4>Wide Dataframe</h4>
<p>Nel formato <strong>wide</strong>, ogni singola riga del dataframe rappresenta un soggetto e ogni sua risposta o variabile misurata sarà riportata in una diversa colonna. In Tabelle <a href="dataframe.html#tab:table-wide-db">10.1</a> vengono presentati i darti dell’esempio in un formato wide.</p>
<table class="table table-striped table-hover table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:table-wide-db">Table 10.1: </span>Dataframe nel formato wong
</caption>
<thead>
<tr>
<th style="text-align:center;">
Id
</th>
<th style="text-align:center;">
age
</th>
<th style="text-align:center;">
gender
</th>
<th style="text-align:center;">
item_1
</th>
<th style="text-align:center;">
item_2
</th>
<th style="text-align:center;">
item_3
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
subj_1
</td>
<td style="text-align:center;">
21
</td>
<td style="text-align:center;">
F
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
2
</td>
</tr>
<tr>
<td style="text-align:center;">
subj_2
</td>
<td style="text-align:center;">
23
</td>
<td style="text-align:center;">
M
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:center;">
subj_3
</td>
<td style="text-align:center;">
19
</td>
<td style="text-align:center;">
F
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
1
</td>
</tr>
</tbody>
</table>
<p>Osserviamo come ogni soggetto si identificato da un codice riportato nella variabile <em>Id</em> e le risposte ai tre item siano riportate in tre diverse variabili <em>item_1</em>, <em>item_2</em> e <em>item_3</em>.</p>
</div>
<div id="long-dataframe" class="section level4 unnumbered">
<h4>Long Dataframe</h4>
<p>Nel formato <strong>long</strong>, ogni singola riga rappresenta una singola osservazione. Quindi i dati di ogni soggetto saranno riportati su più righe e le variabili che non cambiano tra le osservazioni saranno ripetute. In Tabelle <a href="dataframe.html#tab:table-long-db">10.2</a> vengono presentati i darti dell’esempio in un formato lide.</p>
<table class="table table-striped table-hover table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:table-long-db">Table 10.2: </span>Dataframe nel formato long
</caption>
<thead>
<tr>
<th style="text-align:center;">
Id
</th>
<th style="text-align:center;">
age
</th>
<th style="text-align:center;">
gender
</th>
<th style="text-align:center;">
item
</th>
<th style="text-align:center;">
response
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
subj_1
</td>
<td style="text-align:center;">
21
</td>
<td style="text-align:center;">
F
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
2
</td>
</tr>
<tr>
<td style="text-align:center;">
subj_1
</td>
<td style="text-align:center;">
21
</td>
<td style="text-align:center;">
F
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
1
</td>
</tr>
<tr>
<td style="text-align:center;">
subj_1
</td>
<td style="text-align:center;">
21
</td>
<td style="text-align:center;">
F
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1
</td>
</tr>
<tr>
<td style="text-align:center;">
subj_2
</td>
<td style="text-align:center;">
23
</td>
<td style="text-align:center;">
M
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:center;">
subj_2
</td>
<td style="text-align:center;">
23
</td>
<td style="text-align:center;">
M
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
2
</td>
</tr>
<tr>
<td style="text-align:center;">
subj_2
</td>
<td style="text-align:center;">
23
</td>
<td style="text-align:center;">
M
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1
</td>
</tr>
<tr>
<td style="text-align:center;">
subj_3
</td>
<td style="text-align:center;">
19
</td>
<td style="text-align:center;">
F
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
2
</td>
</tr>
<tr>
<td style="text-align:center;">
subj_3
</td>
<td style="text-align:center;">
19
</td>
<td style="text-align:center;">
F
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:center;">
subj_3
</td>
<td style="text-align:center;">
19
</td>
<td style="text-align:center;">
F
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1
</td>
</tr>
</tbody>
</table>
<p>Osserviamo come le risposte di ogni soggetto siano distribuite su più righe. Le caratterische che non variano vengono ripetute ad ogni riga (<em>Id</em>, <em>age</em> e <em>gender</em>) mentre le risposte agli item vengono registrate utilizzando due colonne <em>item</em>, ovvero il numero dell’item, e <em>response</em> l’effettiva risposta di quel partecipante a quello specifico item.</p>
<div class="tip" title="Long o Wide?">
<p>I dati in forma long e wide hanno delle proprietà diverse sopratutto in riferimento all’utilizzo. La tipologia di dato e il risultato finale è esattamente lo stesso tuttavia alcuni software o alcuni pacchetti di R funzionano solo con dataset organizzati in un certo modo.</p>
<p>Non c’è quindi un formato corretto o sbagliato ma dipende dal tipo di analisi e dal software o pacchetto che si utilizza. Alcune operazioni o analisi richiedono il dataset in forma <strong>long</strong> altre in forma <strong>wide</strong>.</p>
<p>Il consiglio però è di abituarsi il più possibile a ragionare in forma <strong>long</strong> perchè la maggior parte dei moderni pacchetti per l’analisi dati e per la creazione di grafici richiedono i dati in questo formato. Ci sono comunque delle funzioni (più avanzate) per passare velocemente da un formato all’altro.</p>
</div>
<p>Nota come nei precedenti esempi abbiamo utilizzato sia colonne che contengono valori numerici numeri sia colonne con caratteri. Questo non era chiaramente possibile con le matrici. Ricorda tuttavia che, come per le matrici, anche i dataframe richiedono che tutte le colonne (variabili) abbiano lo stesso numero di elementi.</p>
<p>Vedremo ora come creare dei dataframe in R e come compiere le comuni operazini di selezione. Infine descriveremo alcune semplici manipolazioni e operazioni con i dataframe. Come vedremo ci sono molte somiglianze nell’utilizzo dei dataframe e delle matrici. Quando necessario, si farà riferimento al capitolo precedente per far notare aspetti in comune e differenze tra queste due strutture di dati.</p>
</div>
<div id="creazione-di-un-dataframe" class="section level2">
<h2><span class="header-section-number">10.1</span> Creazione di un dataframe</h2>
<p>Il comando per creare un dataframe è <code>data.frame()</code>:</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="dataframe.html#cb190-1"></a>nome_df &lt;-<span class="st"> </span><span class="kw">data.frame</span>(</span>
<span id="cb190-2"><a href="dataframe.html#cb190-2"></a>  <span class="dt">variable1 =</span> <span class="kw">c</span>(...),</span>
<span id="cb190-3"><a href="dataframe.html#cb190-3"></a>  <span class="dt">variable2 =</span> <span class="kw">c</span>(...),</span>
<span id="cb190-4"><a href="dataframe.html#cb190-4"></a>  ...)</span></code></pre></div>
<p>La creazione è leggermente diversa rispetto al caso delle matrici. Intuitivamente è più facile immaginarla come l’unione di diverse colonne (dove una può contenere dei nomi, un’altra delle date e così via) piuttosto che un insieme di valori inseriti per riga o per colonna come per le matrici. Infatti per creare un <code>dataframe</code> è proprio necessario specificare le colonne una alla volta, indicando <code>nome_colonna = valori</code> all’interno del comando <code>data.frame()</code>. Vediamo un esempio in R,</p>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="dataframe.html#cb191-1"></a>my_data &lt;-<span class="st"> </span><span class="kw">data.frame</span>(</span>
<span id="cb191-2"><a href="dataframe.html#cb191-2"></a>  <span class="dt">Id =</span> <span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>),</span>
<span id="cb191-3"><a href="dataframe.html#cb191-3"></a>  <span class="dt">names =</span> <span class="kw">c</span>(<span class="st">&quot;Alice&quot;</span>, <span class="st">&quot;Bruno&quot;</span>, <span class="st">&quot;Carla&quot;</span>, <span class="st">&quot;Diego&quot;</span>, <span class="st">&quot;Elisa&quot;</span>),</span>
<span id="cb191-4"><a href="dataframe.html#cb191-4"></a>  <span class="dt">gender =</span> <span class="kw">factor</span>(<span class="kw">c</span>(<span class="st">&quot;F&quot;</span>,<span class="st">&quot;M&quot;</span>,<span class="st">&quot;F&quot;</span>, <span class="st">&quot;M&quot;</span>, <span class="st">&quot;F&quot;</span>)),</span>
<span id="cb191-5"><a href="dataframe.html#cb191-5"></a>  <span class="dt">age =</span> <span class="kw">c</span>(<span class="dv">22</span>, <span class="dv">25</span>, <span class="dv">23</span>, <span class="dv">22</span>, <span class="dv">24</span>),</span>
<span id="cb191-6"><a href="dataframe.html#cb191-6"></a>  <span class="dt">faculty =</span> <span class="kw">factor</span>(<span class="kw">c</span>(<span class="st">&quot;Psicologia&quot;</span>, <span class="st">&quot;Ingegneria&quot;</span>, <span class="st">&quot;Medicina&quot;</span>, <span class="st">&quot;Lettere&quot;</span>, <span class="st">&quot;Psicologia&quot;</span>))</span>
<span id="cb191-7"><a href="dataframe.html#cb191-7"></a>)</span>
<span id="cb191-8"><a href="dataframe.html#cb191-8"></a></span>
<span id="cb191-9"><a href="dataframe.html#cb191-9"></a>my_data</span>
<span id="cb191-10"><a href="dataframe.html#cb191-10"></a><span class="co">##   Id names gender age    faculty</span></span>
<span id="cb191-11"><a href="dataframe.html#cb191-11"></a><span class="co">## 1  1 Alice      F  22 Psicologia</span></span>
<span id="cb191-12"><a href="dataframe.html#cb191-12"></a><span class="co">## 2  2 Bruno      M  25 Ingegneria</span></span>
<span id="cb191-13"><a href="dataframe.html#cb191-13"></a><span class="co">## 3  3 Carla      F  23   Medicina</span></span>
<span id="cb191-14"><a href="dataframe.html#cb191-14"></a><span class="co">## 4  4 Diego      M  22    Lettere</span></span>
<span id="cb191-15"><a href="dataframe.html#cb191-15"></a><span class="co">## 5  5 Elisa      F  24 Psicologia</span></span></code></pre></div>
<p>In questo caso abbiamo creato un ipotetico dataframe dove in ogni riga abbiamo un soggetto e ogni colonna rappresenta una data caratteristica del soggetto come il genere, l’età e così via.</p>
<div class="tip" title="ID">
<p>E’ sempre consigliato definire una colonna (e.g., <code>Id</code>) in cui assegnnare un idenificativo univoco ad ogni soggetto. Questo ci permetto di poterlo indentificare senza correre il rischio di compiere errori. Ad esempio l’utlizzo del nome (o anche nome e cognome) potrebbe non essere indicato poichè più persone potrebbero avere lo stesso nome e non saremo quindi in grado di discriminare i due soggetti.</p>
</div>
<div class="warning" title="stringsAsFactors">
<p>Una variabile di caratteri all’interno di un DataFrame è considerata di default come una semplice sequenza di caratteri. E’ possibile specificare l’argomento <code>stringsAsFactors = TRUE</code> per ottenere che tutte le variabili di caratteri siano considerate come delle variabili catgoriali creando automaticamente dei fattori (vedi Capitolo <a href="factor.html#factor">8</a>).</p>
<p>Nota come il comportamento di default sia differente a seconda della versione di R. Versioni precedenti a R 4.0 avevano infatti come default <code>stringsAsFactors = TRUE</code> mentre dalla 4.0 in poi abbiamo <code>stringsAsFactors = FALSE</code>.</p>
<p>Presta quindi molta attenzione quando utilizzi codici e soluzioni scritte prima della versione 4.0.</p>
</div>
<div id="esercizi-9" class="section level3 unnumbered">
<h3>Esercizi</h3>
<p>Esegui i seguenti esercizi (<a href="https://github.com/psicostat/Introduction2R/blob/master/exercises/chapter-10-dataframe.R">soluzioni</a>):</p>
<ol style="list-style-type: decimal">
<li>Crea il dataframe <code>data_wide</code> riportato in Tabella <a href="dataframe.html#tab:table-wide-db">10.1</a></li>
<li>Crea il dataframe <code>data_long</code> riportato in Tabella <a href="dataframe.html#tab:table-long-db">10.2</a></li>
</ol>
</div>
</div>
<div id="sel-df" class="section level2">
<h2><span class="header-section-number">10.2</span> Selezione Elementi</h2>
<p>Per selezionare uno o pù valori da un dataframe è possibile, in modo analogo alle matrici, utilizzare gli indici di riga e di colonna all’interno delle parentesi quadre:</p>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb192-1"><a href="dataframe.html#cb192-1"></a>nome_dataframe[<span class="op">&lt;</span>indice<span class="op">-</span>riga<span class="op">&gt;</span>, <span class="op">&lt;</span>indice<span class="op">-</span>colonna<span class="op">&gt;</span>]</span></code></pre></div>
<p>Ricordiamo che l’ordine <code>[&lt;indice-riga&gt;, &lt;indice-colonna&gt;]</code> è prestabilito e deve essere rispettato affinché la selezione avvenga correttamente. Possiamo quindi eseguire diverse tipologie di selezioni a seconda delle necessità ussanto le stesse procedure viste per le matrici. Ad esempio, riprendeno il dataframe <code>my_data</code> creato precedentemente possiamo selezionare:</p>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb193-1"><a href="dataframe.html#cb193-1"></a>my_data</span>
<span id="cb193-2"><a href="dataframe.html#cb193-2"></a><span class="co">##    Id    names gender age    faculty</span></span>
<span id="cb193-3"><a href="dataframe.html#cb193-3"></a><span class="co">## 1   1    Alice      F  22 Psicologia</span></span>
<span id="cb193-4"><a href="dataframe.html#cb193-4"></a><span class="co">## 2   2    Bruno      M  25 Ingegneria</span></span>
<span id="cb193-5"><a href="dataframe.html#cb193-5"></a><span class="co">## 3   3    Carla      F  23   Medicina</span></span>
<span id="cb193-6"><a href="dataframe.html#cb193-6"></a><span class="co">## 4   4    Diego      M  22    Lettere</span></span>
<span id="cb193-7"><a href="dataframe.html#cb193-7"></a><span class="co">## 5   5    Elisa      F  24 Psicologia</span></span>
<span id="cb193-8"><a href="dataframe.html#cb193-8"></a><span class="co">## 6   6 Fabrizio      M  35    Lettere</span></span>
<span id="cb193-9"><a href="dataframe.html#cb193-9"></a><span class="co">## 7   7   Gloria      F  26 Ingegneria</span></span>
<span id="cb193-10"><a href="dataframe.html#cb193-10"></a><span class="co">## 8   8   Herman      M  20 Psicologia</span></span>
<span id="cb193-11"><a href="dataframe.html#cb193-11"></a><span class="co">## 9   9    Irene      F  23 Statistica</span></span>
<span id="cb193-12"><a href="dataframe.html#cb193-12"></a><span class="co">## 10 10     Luca      M  22 Ingegneria</span></span>
<span id="cb193-13"><a href="dataframe.html#cb193-13"></a></span>
<span id="cb193-14"><a href="dataframe.html#cb193-14"></a><span class="co"># Valore 3° riga e 2° colonna</span></span>
<span id="cb193-15"><a href="dataframe.html#cb193-15"></a>my_data[<span class="dv">3</span>,<span class="dv">4</span>]</span>
<span id="cb193-16"><a href="dataframe.html#cb193-16"></a><span class="co">## [1] 23</span></span>
<span id="cb193-17"><a href="dataframe.html#cb193-17"></a></span>
<span id="cb193-18"><a href="dataframe.html#cb193-18"></a><span class="co"># Tutte le variabili della 1° e 3° riga</span></span>
<span id="cb193-19"><a href="dataframe.html#cb193-19"></a>my_data[<span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">3</span>), ]</span>
<span id="cb193-20"><a href="dataframe.html#cb193-20"></a><span class="co">##   Id names gender age    faculty</span></span>
<span id="cb193-21"><a href="dataframe.html#cb193-21"></a><span class="co">## 2  2 Bruno      M  25 Ingegneria</span></span>
<span id="cb193-22"><a href="dataframe.html#cb193-22"></a><span class="co">## 3  3 Carla      F  23   Medicina</span></span>
<span id="cb193-23"><a href="dataframe.html#cb193-23"></a></span>
<span id="cb193-24"><a href="dataframe.html#cb193-24"></a><span class="co"># Tutti i valori della 5° variabile</span></span>
<span id="cb193-25"><a href="dataframe.html#cb193-25"></a>my_data[ , <span class="dv">5</span>]</span>
<span id="cb193-26"><a href="dataframe.html#cb193-26"></a><span class="co">##  [1] Psicologia Ingegneria Medicina   Lettere    Psicologia Lettere   </span></span>
<span id="cb193-27"><a href="dataframe.html#cb193-27"></a><span class="co">##  [7] Ingegneria Psicologia Statistica Ingegneria</span></span>
<span id="cb193-28"><a href="dataframe.html#cb193-28"></a><span class="co">## Levels: Ingegneria Lettere Medicina Psicologia Statistica</span></span>
<span id="cb193-29"><a href="dataframe.html#cb193-29"></a></span>
<span id="cb193-30"><a href="dataframe.html#cb193-30"></a><span class="co"># I valori della 2° e 4° variabile per la 3° e 5° riga</span></span>
<span id="cb193-31"><a href="dataframe.html#cb193-31"></a>my_data[<span class="kw">c</span>(<span class="dv">3</span>,<span class="dv">5</span>), <span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">4</span>)]</span>
<span id="cb193-32"><a href="dataframe.html#cb193-32"></a><span class="co">##   names age</span></span>
<span id="cb193-33"><a href="dataframe.html#cb193-33"></a><span class="co">## 3 Carla  23</span></span>
<span id="cb193-34"><a href="dataframe.html#cb193-34"></a><span class="co">## 5 Elisa  24</span></span></code></pre></div>
<p>Tuttavia, nell’utilizzo dei dataframe è più comune indicare i nomi delle variabili e le condizioni logico relazionali per selezionare i valori di interesse.</p>
<div id="selezione-colonne-con-nomi-delle-variabili" class="section level4 unnumbered">
<h4>Selezione Colonne con Nomi delle Variabili</h4>
<p>Una granade differenza tra le matrici ed i dataframe sta nel poter accedere alle colonne utilizzando l’operatore <code>$</code> ed indicando il loro nome attraverso la seguente sintassi:</p>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb194-1"><a href="dataframe.html#cb194-1"></a>nome_dataframe<span class="op">$</span>nome_variabile</span></code></pre></div>
<p>In questo modo accediamo direttamente a quella specifica colonna senza utilizzare indici e parentesi quadre. Ad esempio:</p>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="dataframe.html#cb195-1"></a><span class="co"># Seleziono la variabile &quot;names&quot;</span></span>
<span id="cb195-2"><a href="dataframe.html#cb195-2"></a>my_data<span class="op">$</span>names</span>
<span id="cb195-3"><a href="dataframe.html#cb195-3"></a><span class="co">##  [1] &quot;Alice&quot;    &quot;Bruno&quot;    &quot;Carla&quot;    &quot;Diego&quot;    &quot;Elisa&quot;    &quot;Fabrizio&quot;</span></span>
<span id="cb195-4"><a href="dataframe.html#cb195-4"></a><span class="co">##  [7] &quot;Gloria&quot;   &quot;Herman&quot;   &quot;Irene&quot;    &quot;Luca&quot;</span></span>
<span id="cb195-5"><a href="dataframe.html#cb195-5"></a></span>
<span id="cb195-6"><a href="dataframe.html#cb195-6"></a><span class="co"># Seleziono la variabile &quot;gender&quot;</span></span>
<span id="cb195-7"><a href="dataframe.html#cb195-7"></a>my_data<span class="op">$</span>faculty</span>
<span id="cb195-8"><a href="dataframe.html#cb195-8"></a><span class="co">##  [1] Psicologia Ingegneria Medicina   Lettere    Psicologia Lettere   </span></span>
<span id="cb195-9"><a href="dataframe.html#cb195-9"></a><span class="co">##  [7] Ingegneria Psicologia Statistica Ingegneria</span></span>
<span id="cb195-10"><a href="dataframe.html#cb195-10"></a><span class="co">## Levels: Ingegneria Lettere Medicina Psicologia Statistica</span></span></code></pre></div>
<p>In alternativa è possibile utilizzare la normale procedura di selezione tramite parentesi quadre indicando al cposto degli indici di colonna i nomi delle variabili desiderate. Questo ci permette di selezionare anche più variabili contemporaneamente, ad esempio:</p>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb196-1"><a href="dataframe.html#cb196-1"></a><span class="co"># Seleziono solo la variabile &quot;names&quot;</span></span>
<span id="cb196-2"><a href="dataframe.html#cb196-2"></a>my_data[ , <span class="st">&quot;names&quot;</span>]</span>
<span id="cb196-3"><a href="dataframe.html#cb196-3"></a><span class="co">##  [1] &quot;Alice&quot;    &quot;Bruno&quot;    &quot;Carla&quot;    &quot;Diego&quot;    &quot;Elisa&quot;    &quot;Fabrizio&quot;</span></span>
<span id="cb196-4"><a href="dataframe.html#cb196-4"></a><span class="co">##  [7] &quot;Gloria&quot;   &quot;Herman&quot;   &quot;Irene&quot;    &quot;Luca&quot;</span></span>
<span id="cb196-5"><a href="dataframe.html#cb196-5"></a></span>
<span id="cb196-6"><a href="dataframe.html#cb196-6"></a><span class="co"># Seleziono la variabile &quot;names&quot;, &quot;gender&quot; e &quot;faculty&quot;</span></span>
<span id="cb196-7"><a href="dataframe.html#cb196-7"></a>my_data[, <span class="kw">c</span>(<span class="st">&quot;names&quot;</span>, <span class="st">&quot;gender&quot;</span>, <span class="st">&quot;faculty&quot;</span>)]</span>
<span id="cb196-8"><a href="dataframe.html#cb196-8"></a><span class="co">##       names gender    faculty</span></span>
<span id="cb196-9"><a href="dataframe.html#cb196-9"></a><span class="co">## 1     Alice      F Psicologia</span></span>
<span id="cb196-10"><a href="dataframe.html#cb196-10"></a><span class="co">## 2     Bruno      M Ingegneria</span></span>
<span id="cb196-11"><a href="dataframe.html#cb196-11"></a><span class="co">## 3     Carla      F   Medicina</span></span>
<span id="cb196-12"><a href="dataframe.html#cb196-12"></a><span class="co">## 4     Diego      M    Lettere</span></span>
<span id="cb196-13"><a href="dataframe.html#cb196-13"></a><span class="co">## 5     Elisa      F Psicologia</span></span>
<span id="cb196-14"><a href="dataframe.html#cb196-14"></a><span class="co">## 6  Fabrizio      M    Lettere</span></span>
<span id="cb196-15"><a href="dataframe.html#cb196-15"></a><span class="co">## 7    Gloria      F Ingegneria</span></span>
<span id="cb196-16"><a href="dataframe.html#cb196-16"></a><span class="co">## 8    Herman      M Psicologia</span></span>
<span id="cb196-17"><a href="dataframe.html#cb196-17"></a><span class="co">## 9     Irene      F Statistica</span></span>
<span id="cb196-18"><a href="dataframe.html#cb196-18"></a><span class="co">## 10     Luca      M Ingegneria</span></span></code></pre></div>
<p>Nota come i nomi delle variabili debbano essere forniti come delle stringhe.</p>
</div>
<div id="selezione-righe-con-condizioni-logiche" class="section level4 unnumbered">
<h4>Selezione Righe con Condizioni Logiche</h4>
<p>Avevamo visto precedentemete nel caso dei vettori e delle matrici come sia possibile costruire delle preposizioni logiche per selezionare solo i valori che rispettino una data condizione. Ora questa funzione si rivela particolarmente utile poichè ci permette di <em>interrogare</em> il nostro dataframe in modo semplice ed intuitivo. Utilizzando una condizione logica possiamo, infatti, <em>filtrare</em> le oservazioni che soddisfano una data condizione ed ottenere solo le informazioni di interesse.</p>
<p>Nella canonica sintassi <code>[&lt;indice-riga&gt;, &lt;indice-colonna&gt;]</code>, gli indici di riga vengono sostituiti con una condizione logica che ci permette di filtrare le righe e al posto degli indici di colonna vengono indicati i nomi delle variabili di interesse. Utilizzeremo quindi la seguente sintassi:</p>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="dataframe.html#cb197-1"></a>nome_dataframe[<span class="op">&lt;</span>condizione_logica_righe<span class="op">&gt;</span>, <span class="op">&lt;</span>nomi_variabili<span class="op">&gt;</span>]</span></code></pre></div>
<p>Vediamo ora degli esempi di selezione:</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="dataframe.html#cb198-1"></a><span class="co"># Tutti i dati di &quot;Diego&quot; (Id == 4)</span></span>
<span id="cb198-2"><a href="dataframe.html#cb198-2"></a>my_data[my_data<span class="op">$</span>Id <span class="op">==</span><span class="st"> </span><span class="dv">4</span>, ]</span>
<span id="cb198-3"><a href="dataframe.html#cb198-3"></a><span class="co">##   Id names gender age faculty</span></span>
<span id="cb198-4"><a href="dataframe.html#cb198-4"></a><span class="co">## 4  4 Diego      M  22 Lettere</span></span>
<span id="cb198-5"><a href="dataframe.html#cb198-5"></a></span>
<span id="cb198-6"><a href="dataframe.html#cb198-6"></a><span class="co"># Tutti i dai delle ragazze</span></span>
<span id="cb198-7"><a href="dataframe.html#cb198-7"></a>my_data[my_data<span class="op">$</span>gender <span class="op">==</span><span class="st"> &quot;F&quot;</span>, ]</span>
<span id="cb198-8"><a href="dataframe.html#cb198-8"></a><span class="co">##   Id  names gender age    faculty</span></span>
<span id="cb198-9"><a href="dataframe.html#cb198-9"></a><span class="co">## 1  1  Alice      F  22 Psicologia</span></span>
<span id="cb198-10"><a href="dataframe.html#cb198-10"></a><span class="co">## 3  3  Carla      F  23   Medicina</span></span>
<span id="cb198-11"><a href="dataframe.html#cb198-11"></a><span class="co">## 5  5  Elisa      F  24 Psicologia</span></span>
<span id="cb198-12"><a href="dataframe.html#cb198-12"></a><span class="co">## 7  7 Gloria      F  26 Ingegneria</span></span>
<span id="cb198-13"><a href="dataframe.html#cb198-13"></a><span class="co">## 9  9  Irene      F  23 Statistica</span></span>
<span id="cb198-14"><a href="dataframe.html#cb198-14"></a></span>
<span id="cb198-15"><a href="dataframe.html#cb198-15"></a><span class="co"># Le facoltà dei soggeti con più di 24 anni</span></span>
<span id="cb198-16"><a href="dataframe.html#cb198-16"></a>my_data[my_data<span class="op">$</span>age <span class="op">&gt;</span><span class="st"> </span><span class="dv">24</span>, <span class="kw">c</span>(<span class="st">&quot;age&quot;</span>, <span class="st">&quot;faculty&quot;</span>)]</span>
<span id="cb198-17"><a href="dataframe.html#cb198-17"></a><span class="co">##   age    faculty</span></span>
<span id="cb198-18"><a href="dataframe.html#cb198-18"></a><span class="co">## 2  25 Ingegneria</span></span>
<span id="cb198-19"><a href="dataframe.html#cb198-19"></a><span class="co">## 6  35    Lettere</span></span>
<span id="cb198-20"><a href="dataframe.html#cb198-20"></a><span class="co">## 7  26 Ingegneria</span></span></code></pre></div>
<p>Nota come, nel definire una condizione logica utilizzano le variabili dello stesso dataframe, sia comunque necessario indicare sempre anche il nome del dataframe. Nel caso precendente avremmo ottenuto un errore indicando semplicemente <code>age &gt; 24</code> poichè così indichiamo l’oggetto <code>age</code> (che non esiste) e non la variabile <code>age</code> contenuta in <code>my_data</code>.</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="dataframe.html#cb199-1"></a>my_data[age <span class="op">&gt;</span><span class="st"> </span><span class="dv">24</span>, <span class="kw">c</span>(<span class="st">&quot;age&quot;</span>, <span class="st">&quot;faculty&quot;</span>)]</span>
<span id="cb199-2"><a href="dataframe.html#cb199-2"></a><span class="co">## Error in `[.data.frame`(my_data, age &gt; 24, c(&quot;age&quot;, &quot;faculty&quot;)): object &#39;age&#39; not found</span></span></code></pre></div>
<p>In modo analogo a quanto visto con i vettori, utlizzando la condizione <code>my_data$age &gt; 24</code> otteniamo un vettore di valori <code>TRUE</code> e <code>FALSE</code> a seconda che la condizione sia rispettata o meno.</p>
<p>Utilizzando gli operatori logici <strong>AND</strong>(<code>&amp;</code>) <strong>OR</strong>(<code>|</code>) e <strong>NOT</strong>(<code>!</code>) possiamo combinare più operazioni logiche insieme per ottenere indicizzazioni più complesse, ma sempre intuitive dal punto di vista della scrittura. Ad esempio, per selezionare “I soggetti tra i 20 e i 25 anni iscrittti a psicologia” eseguiremo:</p>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="dataframe.html#cb200-1"></a>my_data[my_data<span class="op">$</span>age <span class="op">&gt;=</span><span class="st"> </span><span class="dv">20</span> <span class="op">&amp;</span><span class="st"> </span>my_data<span class="op">$</span>age <span class="op">&lt;=</span><span class="dv">25</span> <span class="op">&amp;</span><span class="st"> </span>my_data<span class="op">$</span>faculty <span class="op">==</span><span class="st"> &quot;Psicologia&quot;</span>, ]</span>
<span id="cb200-2"><a href="dataframe.html#cb200-2"></a><span class="co">##   Id  names gender age    faculty</span></span>
<span id="cb200-3"><a href="dataframe.html#cb200-3"></a><span class="co">## 1  1  Alice      F  22 Psicologia</span></span>
<span id="cb200-4"><a href="dataframe.html#cb200-4"></a><span class="co">## 5  5  Elisa      F  24 Psicologia</span></span>
<span id="cb200-5"><a href="dataframe.html#cb200-5"></a><span class="co">## 8  8 Herman      M  20 Psicologia</span></span></code></pre></div>
<p>Utilizzando questo metodo di indicizzazione possiamo apprezzare la vera potenza dei dataframe. Abbiamo, infatti, un metodo molto semplice ed intuitivo per lavorare con strutture di dati complesse formate da diverse tipologie di dati.</p>
<div class="design" title="Output Selezione">
<p>Due aspetti importanti riguardanti il risultato di una selezione sono la tipologia di ouput ottenuto e come salvarla.</p>
<h4 id="tiplogia-output" class="unnumbered">Tiplogia Output</h4>
<p>In modo analogo alle matrici, i comandi di selezione non restituiscono sempre la stessa tipologia di oggetto. Infatti, quando selezioniamo una singola variabile otteniamo come risultato un vettore mentre selezionando due o più variabili oteniamo un dataframe.</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="dataframe.html#cb201-1"></a><span class="co"># Singola variabile</span></span>
<span id="cb201-2"><a href="dataframe.html#cb201-2"></a><span class="kw">class</span>(my_data<span class="op">$</span>age)</span>
<span id="cb201-3"><a href="dataframe.html#cb201-3"></a><span class="co">## [1] &quot;numeric&quot;</span></span>
<span id="cb201-4"><a href="dataframe.html#cb201-4"></a></span>
<span id="cb201-5"><a href="dataframe.html#cb201-5"></a><span class="co"># Più variabili</span></span>
<span id="cb201-6"><a href="dataframe.html#cb201-6"></a><span class="kw">class</span>(my_data[ , <span class="kw">c</span>(<span class="st">&quot;names&quot;</span>, <span class="st">&quot;age&quot;</span>)])</span>
<span id="cb201-7"><a href="dataframe.html#cb201-7"></a><span class="co">## [1] &quot;data.frame&quot;</span></span></code></pre></div>
<h4 id="salvare-selezione" class="unnumbered">Salvare Selezione</h4>
<p>Come per tutte le altre tipologie di oggetti, le operazioni di selezione non modificano l’oggetto iniziale. Pertanto è necessario salvare il risultato della selezione se si desidera mantenere le modifiche. In questo caso, è cosigliabile creare un nuovo oggetto e non sovrascrivere l’oggetto iniziale poichè non ci permetterebbe di compiere nuove selezioni od operazioni su tutti i dati iniziali. E’ buona norma quindi mantenere sempre un dataframe con la versione dei dati originali.</p>
</div>
</div>
<div id="utilizzi-avanzati-selezione" class="section level3">
<h3><span class="header-section-number">10.2.1</span> Utilizzi Avanzati Selezione</h3>
<p>Vediamo ora alcuni utilizzi avanzati della selezione di elementi di un dataframe.</p>
<div id="modificare-gli-elementi-2" class="section level4 unnumbered">
<h4>Modificare gli Elementi</h4>
<p>In modo analogo agli altri oggetti, possiamo modificare dei valori selezionando il vecchio valore della matrice e utilizzo la funzione <code>&lt;-</code> (o <code>=</code>) per assegnare il nuovo valore.</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="dataframe.html#cb202-1"></a>my_data[<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>, ]</span>
<span id="cb202-2"><a href="dataframe.html#cb202-2"></a><span class="co">##   Id names gender age    faculty</span></span>
<span id="cb202-3"><a href="dataframe.html#cb202-3"></a><span class="co">## 1  1 Alice      F  22 Psicologia</span></span>
<span id="cb202-4"><a href="dataframe.html#cb202-4"></a><span class="co">## 2  2 Bruno      M  25 Ingegneria</span></span>
<span id="cb202-5"><a href="dataframe.html#cb202-5"></a><span class="co">## 3  3 Carla      F  23   Medicina</span></span>
<span id="cb202-6"><a href="dataframe.html#cb202-6"></a><span class="co">## 4  4 Diego      M  22    Lettere</span></span>
<span id="cb202-7"><a href="dataframe.html#cb202-7"></a><span class="co">## 5  5 Elisa      F  24 Psicologia</span></span>
<span id="cb202-8"><a href="dataframe.html#cb202-8"></a></span>
<span id="cb202-9"><a href="dataframe.html#cb202-9"></a><span class="co"># Sostituisco il nome &quot;Diego&quot; con &quot;Davide&quot;</span></span>
<span id="cb202-10"><a href="dataframe.html#cb202-10"></a>my_data[<span class="dv">4</span>, <span class="st">&quot;names&quot;</span>] &lt;-<span class="st"> &quot;Davide&quot;</span></span>
<span id="cb202-11"><a href="dataframe.html#cb202-11"></a></span>
<span id="cb202-12"><a href="dataframe.html#cb202-12"></a>my_data[<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>]</span>
<span id="cb202-13"><a href="dataframe.html#cb202-13"></a><span class="co">##    Id    names gender age    faculty</span></span>
<span id="cb202-14"><a href="dataframe.html#cb202-14"></a><span class="co">## 1   1    Alice      F  22 Psicologia</span></span>
<span id="cb202-15"><a href="dataframe.html#cb202-15"></a><span class="co">## 2   2    Bruno      M  25 Ingegneria</span></span>
<span id="cb202-16"><a href="dataframe.html#cb202-16"></a><span class="co">## 3   3    Carla      F  23   Medicina</span></span>
<span id="cb202-17"><a href="dataframe.html#cb202-17"></a><span class="co">## 4   4   Davide      M  22    Lettere</span></span>
<span id="cb202-18"><a href="dataframe.html#cb202-18"></a><span class="co">## 5   5    Elisa      F  24 Psicologia</span></span>
<span id="cb202-19"><a href="dataframe.html#cb202-19"></a><span class="co">## 6   6 Fabrizio      M  35    Lettere</span></span>
<span id="cb202-20"><a href="dataframe.html#cb202-20"></a><span class="co">## 7   7   Gloria      F  26 Ingegneria</span></span>
<span id="cb202-21"><a href="dataframe.html#cb202-21"></a><span class="co">## 8   8   Herman      M  20 Psicologia</span></span>
<span id="cb202-22"><a href="dataframe.html#cb202-22"></a><span class="co">## 9   9    Irene      F  23 Statistica</span></span>
<span id="cb202-23"><a href="dataframe.html#cb202-23"></a><span class="co">## 10 10     Luca      M  22 Ingegneria</span></span></code></pre></div>
</div>
<div id="eliminare-righe-o-colonne-1" class="section level4 unnumbered">
<h4>Eliminare Righe o Colonne</h4>
<p>In modo analogo agli altri oggetti, per <strong>eliminare</strong> delle righe (o delle colonne) da un dataframe, è necessario indicare all’interno delle parentesi quadre gli indici di riga (o di colonna) che si intende eliminare, preceduti dall’operatore <code>-</code> (<em>meno</em>). Nel caso di più righe (o colone) è possibile indicare il meno solo prima del comando <code>c()</code>.</p>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="dataframe.html#cb203-1"></a><span class="co"># Elimino le variabili &quot;gender&quot; e &quot;age&quot;</span></span>
<span id="cb203-2"><a href="dataframe.html#cb203-2"></a>my_data[ , <span class="kw">c</span>(<span class="st">&quot;gender&quot;</span>, <span class="st">&quot;age&quot;</span>)]</span>
<span id="cb203-3"><a href="dataframe.html#cb203-3"></a><span class="co">##    gender age</span></span>
<span id="cb203-4"><a href="dataframe.html#cb203-4"></a><span class="co">## 1       F  22</span></span>
<span id="cb203-5"><a href="dataframe.html#cb203-5"></a><span class="co">## 2       M  25</span></span>
<span id="cb203-6"><a href="dataframe.html#cb203-6"></a><span class="co">## 3       F  23</span></span>
<span id="cb203-7"><a href="dataframe.html#cb203-7"></a><span class="co">## 4       M  22</span></span>
<span id="cb203-8"><a href="dataframe.html#cb203-8"></a><span class="co">## 5       F  24</span></span>
<span id="cb203-9"><a href="dataframe.html#cb203-9"></a><span class="co">## 6       M  35</span></span>
<span id="cb203-10"><a href="dataframe.html#cb203-10"></a><span class="co">## 7       F  26</span></span>
<span id="cb203-11"><a href="dataframe.html#cb203-11"></a><span class="co">## 8       M  20</span></span>
<span id="cb203-12"><a href="dataframe.html#cb203-12"></a><span class="co">## 9       F  23</span></span>
<span id="cb203-13"><a href="dataframe.html#cb203-13"></a><span class="co">## 10      M  22</span></span>
<span id="cb203-14"><a href="dataframe.html#cb203-14"></a></span>
<span id="cb203-15"><a href="dataframe.html#cb203-15"></a><span class="co"># Elimino le prime 5 osservazioni</span></span>
<span id="cb203-16"><a href="dataframe.html#cb203-16"></a>my_data[<span class="op">-</span><span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>), ]</span>
<span id="cb203-17"><a href="dataframe.html#cb203-17"></a><span class="co">##    Id    names gender age    faculty</span></span>
<span id="cb203-18"><a href="dataframe.html#cb203-18"></a><span class="co">## 6   6 Fabrizio      M  35    Lettere</span></span>
<span id="cb203-19"><a href="dataframe.html#cb203-19"></a><span class="co">## 7   7   Gloria      F  26 Ingegneria</span></span>
<span id="cb203-20"><a href="dataframe.html#cb203-20"></a><span class="co">## 8   8   Herman      M  20 Psicologia</span></span>
<span id="cb203-21"><a href="dataframe.html#cb203-21"></a><span class="co">## 9   9    Irene      F  23 Statistica</span></span>
<span id="cb203-22"><a href="dataframe.html#cb203-22"></a><span class="co">## 10 10     Luca      M  22 Ingegneria</span></span>
<span id="cb203-23"><a href="dataframe.html#cb203-23"></a></span>
<span id="cb203-24"><a href="dataframe.html#cb203-24"></a><span class="co"># Elimino le prime 5 osservazioni e la variabile &quot;names&quot;</span></span>
<span id="cb203-25"><a href="dataframe.html#cb203-25"></a>my_data[<span class="op">-</span><span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>), <span class="dv">-3</span>]</span>
<span id="cb203-26"><a href="dataframe.html#cb203-26"></a><span class="co">##    Id    names age    faculty</span></span>
<span id="cb203-27"><a href="dataframe.html#cb203-27"></a><span class="co">## 6   6 Fabrizio  35    Lettere</span></span>
<span id="cb203-28"><a href="dataframe.html#cb203-28"></a><span class="co">## 7   7   Gloria  26 Ingegneria</span></span>
<span id="cb203-29"><a href="dataframe.html#cb203-29"></a><span class="co">## 8   8   Herman  20 Psicologia</span></span>
<span id="cb203-30"><a href="dataframe.html#cb203-30"></a><span class="co">## 9   9    Irene  23 Statistica</span></span>
<span id="cb203-31"><a href="dataframe.html#cb203-31"></a><span class="co">## 10 10     Luca  22 Ingegneria</span></span></code></pre></div>
<p>E’ possibile anche escludere (ed eliminare in un certo senso) delle informazioni usando gli operatori logici in gli operatori <strong>NOT</strong>(<code>!</code>) e diverso da (<code>!=</code>):</p>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="dataframe.html#cb204-1"></a><span class="co"># Seleziono tutto tranne gli studenti di psicologia</span></span>
<span id="cb204-2"><a href="dataframe.html#cb204-2"></a></span>
<span id="cb204-3"><a href="dataframe.html#cb204-3"></a><span class="co"># Modo 1 (valuto disuguaglianza)</span></span>
<span id="cb204-4"><a href="dataframe.html#cb204-4"></a>my_data[my_data<span class="op">$</span>faculty <span class="op">!=</span><span class="st"> &quot;Psicologia&quot;</span>, ]</span>
<span id="cb204-5"><a href="dataframe.html#cb204-5"></a><span class="co">##    Id    names gender age    faculty</span></span>
<span id="cb204-6"><a href="dataframe.html#cb204-6"></a><span class="co">## 2   2    Bruno      M  25 Ingegneria</span></span>
<span id="cb204-7"><a href="dataframe.html#cb204-7"></a><span class="co">## 3   3    Carla      F  23   Medicina</span></span>
<span id="cb204-8"><a href="dataframe.html#cb204-8"></a><span class="co">## 4   4   Davide      M  22    Lettere</span></span>
<span id="cb204-9"><a href="dataframe.html#cb204-9"></a><span class="co">## 6   6 Fabrizio      M  35    Lettere</span></span>
<span id="cb204-10"><a href="dataframe.html#cb204-10"></a><span class="co">## 7   7   Gloria      F  26 Ingegneria</span></span>
<span id="cb204-11"><a href="dataframe.html#cb204-11"></a><span class="co">## 9   9    Irene      F  23 Statistica</span></span>
<span id="cb204-12"><a href="dataframe.html#cb204-12"></a><span class="co">## 10 10     Luca      M  22 Ingegneria</span></span>
<span id="cb204-13"><a href="dataframe.html#cb204-13"></a></span>
<span id="cb204-14"><a href="dataframe.html#cb204-14"></a><span class="co"># Modo 1 (nego l&#39;uguaglianza)</span></span>
<span id="cb204-15"><a href="dataframe.html#cb204-15"></a>my_data[<span class="op">!</span>my_data<span class="op">$</span>faculty <span class="op">==</span><span class="st"> &quot;Psicologia&quot;</span>, ]</span>
<span id="cb204-16"><a href="dataframe.html#cb204-16"></a><span class="co">##    Id    names gender age    faculty</span></span>
<span id="cb204-17"><a href="dataframe.html#cb204-17"></a><span class="co">## 2   2    Bruno      M  25 Ingegneria</span></span>
<span id="cb204-18"><a href="dataframe.html#cb204-18"></a><span class="co">## 3   3    Carla      F  23   Medicina</span></span>
<span id="cb204-19"><a href="dataframe.html#cb204-19"></a><span class="co">## 4   4   Davide      M  22    Lettere</span></span>
<span id="cb204-20"><a href="dataframe.html#cb204-20"></a><span class="co">## 6   6 Fabrizio      M  35    Lettere</span></span>
<span id="cb204-21"><a href="dataframe.html#cb204-21"></a><span class="co">## 7   7   Gloria      F  26 Ingegneria</span></span>
<span id="cb204-22"><a href="dataframe.html#cb204-22"></a><span class="co">## 9   9    Irene      F  23 Statistica</span></span>
<span id="cb204-23"><a href="dataframe.html#cb204-23"></a><span class="co">## 10 10     Luca      M  22 Ingegneria</span></span></code></pre></div>
<p>Nota come l’operazione di eliminazione sia comunque un’operazione di selezione. Pertanto è necessario salvare il risultato ottenuto se si desidera mantenere le modifiche.</p>
<div class="warning" title="Attenzione ad Eliminare">
<p>L’utilizzo dell’operatore <code>-</code> è sempre in qualche modo pericoloso, sopratutto se l’oggetto che viene creato (o sovrascritto) viene poi utilizzato in altre operazioni. Eliminare delle informazioni, tranne quando è veramente necessario, non è mai una buona cosa. Se dovete selezionare una parte dei dati è sempre meglio creare un nuovo dataframe (o un nuovo oggetto in generale) e mantendere una versione di quello originale sempre disponibile.</p>
</div>
</div>
</div>
<div id="esercizi-10" class="section level3 unnumbered">
<h3>Esercizi</h3>
<p>Facendo riferimento ai dataframe <code>data_long</code> e <code>data_wide</code> precedentemente creati, esegui i seguenti esercizi (<a href="https://github.com/psicostat/Introduction2R/blob/master/exercises/chapter-10-dataframe.R">soluzioni</a>):</p>
<ol style="list-style-type: decimal">
<li>Utilizzando gli <strong>indici numerici</strong> di riga e di colonna seleziona i dati del soggetto <code>subj_2</code> riguardanti le variabili <code>item</code> e <code>response</code> dal DataFrame <code>data_long</code>.</li>
<li>Compi la stessa selezione dell’esercizio precedente usando però questa volta una condizione logica per gli indici di riga e indicando direttamente il nome delle variabili per gli indici di colonna.</li>
<li>Considerando il DataFrame <code>data_wide</code> seleziona le variabili <code>Id</code> e <code>gender</code> dei soggetti che hanno risposto 1 alla variabile <code>item_1</code>.</li>
<li>Considerando il DataFrame <code>data_long</code> seleziona solamente i dati riguardanti le ragazze con etè superiore ai 20 anni.</li>
<li>Elimina dal DataFrame <code>data_long</code> le osservazioni riguardanti il soggetto <code>subj_2</code> e la variabile <code>"gender"</code>.</li>
</ol>
</div>
</div>
<div id="funzioni-ed-operazioni-1" class="section level2">
<h2><span class="header-section-number">10.3</span> Funzioni ed Operazioni</h2>
<p>Vediamo ora alcune funzioni frequentemente usate e le comuni operazioni eseguite con i dataframe (vedi Tabella <a href="dataframe.html#tab:table-df-functions">10.3</a>).</p>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:table-df-functions">Table 10.3: </span>Funzioni e operazioni con dataframe
</caption>
<thead>
<tr>
<th style="text-align:left;">
Funzione
</th>
<th style="text-align:left;">
Descrizione
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
nrow(nome_df)
</td>
<td style="text-align:left;">
Numero di osservazioni del dataframe
</td>
</tr>
<tr>
<td style="text-align:left;">
ncol(nome_df)
</td>
<td style="text-align:left;">
Numero di variabili del dataframe
</td>
</tr>
<tr>
<td style="text-align:left;">
colnames(nome_df)
</td>
<td style="text-align:left;">
Nomi delle colonne del dataframe
</td>
</tr>
<tr>
<td style="text-align:left;">
rownames(nome_df)
</td>
<td style="text-align:left;">
Nomi delle righe del dataframe
</td>
</tr>
<tr>
<td style="text-align:left;">
nome_df &lt;-<br> cbind(nome_df, dati) <br> nome_df$nome_var &lt;-<br> dati
</td>
<td style="text-align:left;">
Aggiungi una nuova variabile al dataframe (deve avere lo stesso numero di righe)
</td>
</tr>
<tr>
<td style="text-align:left;">
nome_df &lt;- rbind(nome_df, dati)
</td>
<td style="text-align:left;">
Aggiungi delle osservazioni (i nuovi dati devono essere coerenti con la struttura del dataframe)
</td>
</tr>
<tr>
<td style="text-align:left;">
head(nome_df)
</td>
<td style="text-align:left;">
Prime righe del dataframe
</td>
</tr>
<tr>
<td style="text-align:left;">
tail(nome_df)
</td>
<td style="text-align:left;">
Ultime righe del dataframe
</td>
</tr>
<tr>
<td style="text-align:left;">
str(nome_df)
</td>
<td style="text-align:left;">
Struttura del dataframe
</td>
</tr>
<tr>
<td style="text-align:left;">
summary(nome_df)
</td>
<td style="text-align:left;">
Summary del dataframe
</td>
</tr>
</tbody>
</table>
<p>Descriviamo ora nel dettaglio alcuni particolari utilizzi, considrando come esempio una versione ridotta del dataframe <code>my_data</code> precedentemente creata.</p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="dataframe.html#cb205-1"></a>data_short &lt;-<span class="st"> </span>my_data[<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>, ]</span>
<span id="cb205-2"><a href="dataframe.html#cb205-2"></a>data_short</span>
<span id="cb205-3"><a href="dataframe.html#cb205-3"></a><span class="co">##   Id  names gender age    faculty</span></span>
<span id="cb205-4"><a href="dataframe.html#cb205-4"></a><span class="co">## 1  1  Alice      F  22 Psicologia</span></span>
<span id="cb205-5"><a href="dataframe.html#cb205-5"></a><span class="co">## 2  2  Bruno      M  25 Ingegneria</span></span>
<span id="cb205-6"><a href="dataframe.html#cb205-6"></a><span class="co">## 3  3  Carla      F  23   Medicina</span></span>
<span id="cb205-7"><a href="dataframe.html#cb205-7"></a><span class="co">## 4  4 Davide      M  22    Lettere</span></span>
<span id="cb205-8"><a href="dataframe.html#cb205-8"></a><span class="co">## 5  5  Elisa      F  24 Psicologia</span></span></code></pre></div>
<div id="attributi-di-un-dataframe" class="section level3">
<h3><span class="header-section-number">10.3.1</span> Attributi di un Dataframe</h3>
<p>Abbiamo visto nel Capitolo <a href="factor.html#attributes">8.1</a> che gli oggetti in R possiedono quelli che sono definiti <em>attributi</em> ovvero delle utili informazioni riguardanti l’oggetto stesso, una sorta di <em>metadata</em>. Vediamo ora, in modo analogo alle matrici, come valutare la dimensione di un dataframe e i nomi delle righe e delle colonne.</p>
<div id="dimensione-2" class="section level4 unnumbered">
<h4>Dimensione</h4>
<p>Ricordiamo che un dataframe è un oggetto <strong>bidimensionale</strong> formato da righe e colonne. Per ottenere il numero di righe e di colonne di un dataframe, possiamo usare rispettivamente i comandi <code>nrow()</code> e <code>ncol()</code>.</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="dataframe.html#cb206-1"></a><span class="co"># Numero di righe</span></span>
<span id="cb206-2"><a href="dataframe.html#cb206-2"></a><span class="kw">nrow</span>(my_data)</span>
<span id="cb206-3"><a href="dataframe.html#cb206-3"></a><span class="co">## [1] 10</span></span>
<span id="cb206-4"><a href="dataframe.html#cb206-4"></a></span>
<span id="cb206-5"><a href="dataframe.html#cb206-5"></a><span class="co"># Numero di colonne</span></span>
<span id="cb206-6"><a href="dataframe.html#cb206-6"></a><span class="kw">ncol</span>(my_data)</span>
<span id="cb206-7"><a href="dataframe.html#cb206-7"></a><span class="co">## [1] 5</span></span></code></pre></div>
<p>In alternativa, come per le matrici, è possibile usare la funzione <code>dim()</code>che restituisce un vettore con due valori dove il primo rappresenta il numero di righe e il secondo il numero di colonne.</p>
</div>
<div id="nomi-righe-e-colonne-1" class="section level4 unnumbered">
<h4>Nomi Righe e Colonne</h4>
<p>In modo simile alle matrici, è possibile accedere ai nomi delle righe e delle colonne utilizzando rispettivamente le funzioni <code>rownames()</code> e <code>colnames()</code>. Di default il dataframe richiede dei nomi solo alle colonne mentre il alle righe viene assegnato un nome in accordo con l’indice di riga. Tuttavia, è possibile anche nominare le righe con valori arbitrari sebbene sia una funzione raramente utilizzata.</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="dataframe.html#cb207-1"></a><span class="co"># Controllo i nomi attuali</span></span>
<span id="cb207-2"><a href="dataframe.html#cb207-2"></a><span class="kw">rownames</span>(data_short)</span>
<span id="cb207-3"><a href="dataframe.html#cb207-3"></a><span class="co">## [1] &quot;1&quot; &quot;2&quot; &quot;3&quot; &quot;4&quot; &quot;5&quot;</span></span>
<span id="cb207-4"><a href="dataframe.html#cb207-4"></a><span class="kw">colnames</span>(data_short)</span>
<span id="cb207-5"><a href="dataframe.html#cb207-5"></a><span class="co">## [1] &quot;Id&quot;      &quot;names&quot;   &quot;gender&quot;  &quot;age&quot;     &quot;faculty&quot;</span></span></code></pre></div>
<p>Per impostare i nomi di righe e/o colonne, sarà quindi necessario assegnare a <code>rownames(nome_dataframe)</code> e <code>colnames(nome_dataframe)</code> un vettore di caratteri della stessa lunghezza della dimensione che stiamo rinominando.</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="dataframe.html#cb208-1"></a><span class="co"># Assegnamo i nomi alle righe</span></span>
<span id="cb208-2"><a href="dataframe.html#cb208-2"></a><span class="kw">rownames</span>(data_short) &lt;-<span class="st"> </span><span class="kw">paste0</span>(<span class="st">&quot;Subj_&quot;</span>, <span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(data_short))</span>
<span id="cb208-3"><a href="dataframe.html#cb208-3"></a></span>
<span id="cb208-4"><a href="dataframe.html#cb208-4"></a><span class="co"># Assegno i nomi alle colonne</span></span>
<span id="cb208-5"><a href="dataframe.html#cb208-5"></a><span class="kw">colnames</span>(data_short) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Id&quot;</span>, <span class="st">&quot;Nome&quot;</span>, <span class="st">&quot;Genere&quot;</span>, <span class="st">&quot;Eta&quot;</span>, <span class="st">&quot;Facolta&quot;</span>)</span>
<span id="cb208-6"><a href="dataframe.html#cb208-6"></a></span>
<span id="cb208-7"><a href="dataframe.html#cb208-7"></a>data_short</span>
<span id="cb208-8"><a href="dataframe.html#cb208-8"></a><span class="co">##        Id   Nome Genere Eta    Facolta</span></span>
<span id="cb208-9"><a href="dataframe.html#cb208-9"></a><span class="co">## Subj_1  1  Alice      F  22 Psicologia</span></span>
<span id="cb208-10"><a href="dataframe.html#cb208-10"></a><span class="co">## Subj_2  2  Bruno      M  25 Ingegneria</span></span>
<span id="cb208-11"><a href="dataframe.html#cb208-11"></a><span class="co">## Subj_3  3  Carla      F  23   Medicina</span></span>
<span id="cb208-12"><a href="dataframe.html#cb208-12"></a><span class="co">## Subj_4  4 Davide      M  22    Lettere</span></span>
<span id="cb208-13"><a href="dataframe.html#cb208-13"></a><span class="co">## Subj_5  5  Elisa      F  24 Psicologia</span></span></code></pre></div>
<p>Infine, nota come la funzione <code>names()</code> nel caso dei dataframe sia analoga alla funzione <code>colnames()</code> e sia possibile usare il vaore <code>NULL</code> per eliminare ad esempio i nomi delle righe.</p>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb209-1"><a href="dataframe.html#cb209-1"></a><span class="kw">names</span>(data_short)</span>
<span id="cb209-2"><a href="dataframe.html#cb209-2"></a><span class="co">## [1] &quot;Id&quot;      &quot;Nome&quot;    &quot;Genere&quot;  &quot;Eta&quot;     &quot;Facolta&quot;</span></span>
<span id="cb209-3"><a href="dataframe.html#cb209-3"></a></span>
<span id="cb209-4"><a href="dataframe.html#cb209-4"></a><span class="kw">rownames</span>(data_short) &lt;-<span class="st"> </span><span class="ot">NULL</span></span>
<span id="cb209-5"><a href="dataframe.html#cb209-5"></a>data_short</span>
<span id="cb209-6"><a href="dataframe.html#cb209-6"></a><span class="co">##   Id   Nome Genere Eta    Facolta</span></span>
<span id="cb209-7"><a href="dataframe.html#cb209-7"></a><span class="co">## 1  1  Alice      F  22 Psicologia</span></span>
<span id="cb209-8"><a href="dataframe.html#cb209-8"></a><span class="co">## 2  2  Bruno      M  25 Ingegneria</span></span>
<span id="cb209-9"><a href="dataframe.html#cb209-9"></a><span class="co">## 3  3  Carla      F  23   Medicina</span></span>
<span id="cb209-10"><a href="dataframe.html#cb209-10"></a><span class="co">## 4  4 Davide      M  22    Lettere</span></span>
<span id="cb209-11"><a href="dataframe.html#cb209-11"></a><span class="co">## 5  5  Elisa      F  24 Psicologia</span></span></code></pre></div>
</div>
</div>
<div id="unire-dataframe" class="section level3">
<h3><span class="header-section-number">10.3.2</span> Unire Dataframe</h3>
<p>In modo analogo alle matrici è possibile unire più dataframe utilizzando le funzioni <code>cbind()</code> e <code>rbind()</code> per cui valgono gli stesssi accorgimenti riguardanti la dimensione rispettivamente di righe e colonne. Tuttavia, nel caso dei dataframe è possibile creare una nuova colonna anche utilizzando l’operatore <code>$</code>. Descriviamo ora in modo accurato i differenti utilizzi.</p>
<div id="dataframename---new_var" class="section level4 unnumbered">
<h4><code>dataframe$name &lt;- new_var</code></h4>
<p>Con la scrittura <code>dataframe$name &lt;- new_var</code> aggiungiamo al dataframe in oggetto una nuova colonna chiamata <code>name</code> che prende i valori all’interno di <code>new_var</code>. Sarà necessario che la nuova variabile abbia lo stesso numero di valori delle righe del dataframe.</p>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="dataframe.html#cb210-1"></a><span class="co"># Aggiungiamo la colonna &quot;media&quot;</span></span>
<span id="cb210-2"><a href="dataframe.html#cb210-2"></a>data_short<span class="op">$</span>Media &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">27.5</span>, <span class="fl">23.6</span>, <span class="fl">28.3</span>, <span class="fl">29.2</span>, <span class="fl">24.8</span>)</span>
<span id="cb210-3"><a href="dataframe.html#cb210-3"></a></span>
<span id="cb210-4"><a href="dataframe.html#cb210-4"></a><span class="co"># Equivalente a</span></span>
<span id="cb210-5"><a href="dataframe.html#cb210-5"></a>media_voti &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">27.5</span>, <span class="fl">23.6</span>, <span class="fl">28.3</span>, <span class="fl">29.2</span>, <span class="fl">24.8</span>)</span>
<span id="cb210-6"><a href="dataframe.html#cb210-6"></a>data_short<span class="op">$</span>Media &lt;-<span class="st"> </span>media_voti</span>
<span id="cb210-7"><a href="dataframe.html#cb210-7"></a></span>
<span id="cb210-8"><a href="dataframe.html#cb210-8"></a>data_short</span>
<span id="cb210-9"><a href="dataframe.html#cb210-9"></a><span class="co">##   Id   Nome Genere Eta    Facolta Media</span></span>
<span id="cb210-10"><a href="dataframe.html#cb210-10"></a><span class="co">## 1  1  Alice      F  22 Psicologia  27.5</span></span>
<span id="cb210-11"><a href="dataframe.html#cb210-11"></a><span class="co">## 2  2  Bruno      M  25 Ingegneria  23.6</span></span>
<span id="cb210-12"><a href="dataframe.html#cb210-12"></a><span class="co">## 3  3  Carla      F  23   Medicina  28.3</span></span>
<span id="cb210-13"><a href="dataframe.html#cb210-13"></a><span class="co">## 4  4 Davide      M  22    Lettere  29.2</span></span>
<span id="cb210-14"><a href="dataframe.html#cb210-14"></a><span class="co">## 5  5  Elisa      F  24 Psicologia  24.8</span></span></code></pre></div>
</div>
<div id="cbind" class="section level4 unnumbered">
<h4><code>cbind()</code></h4>
<p>Con la funzione <code>cbind()</code> possiamo aggiungere una o più variabili al nostro dataframe. Nota come a differenza dell’utilizzo dell’operatore <code>$,</code>usando <code>cbind()</code> il risultato non venga automaticamente salvato ma sia necessario assegnare l’operazione ad un nuovo oggetto <code>dataframe &lt;- cbind(dataframe, new_var)</code>. In quest’ultimo caso il nome della colonna sarà <code>new_var</code>. Se vogliamo anche rinominare la colonna possiamo usare la sintassi <code>cbind(dataframe, "nome" = new_var)</code> oppure chiamare l’oggetto direttamente con il nome desiderato:</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="dataframe.html#cb211-1"></a><span class="co"># aggiungo la variabile Numero_esami</span></span>
<span id="cb211-2"><a href="dataframe.html#cb211-2"></a>numero_esami &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">12</span>, <span class="dv">14</span>, <span class="dv">13</span>, <span class="dv">10</span>, <span class="dv">8</span>)</span>
<span id="cb211-3"><a href="dataframe.html#cb211-3"></a></span>
<span id="cb211-4"><a href="dataframe.html#cb211-4"></a><span class="kw">cbind</span>(data_short, numero_esami) <span class="co"># senza specificare il nome</span></span>
<span id="cb211-5"><a href="dataframe.html#cb211-5"></a><span class="co">##   Id   Nome Genere Eta    Facolta Media numero_esami</span></span>
<span id="cb211-6"><a href="dataframe.html#cb211-6"></a><span class="co">## 1  1  Alice      F  22 Psicologia  27.5           12</span></span>
<span id="cb211-7"><a href="dataframe.html#cb211-7"></a><span class="co">## 2  2  Bruno      M  25 Ingegneria  23.6           14</span></span>
<span id="cb211-8"><a href="dataframe.html#cb211-8"></a><span class="co">## 3  3  Carla      F  23   Medicina  28.3           13</span></span>
<span id="cb211-9"><a href="dataframe.html#cb211-9"></a><span class="co">## 4  4 Davide      M  22    Lettere  29.2           10</span></span>
<span id="cb211-10"><a href="dataframe.html#cb211-10"></a><span class="co">## 5  5  Elisa      F  24 Psicologia  24.8            8</span></span>
<span id="cb211-11"><a href="dataframe.html#cb211-11"></a></span>
<span id="cb211-12"><a href="dataframe.html#cb211-12"></a><span class="kw">cbind</span>(data_short, <span class="st">&quot;N_esami&quot;</span> =<span class="st"> </span>numero_esami) <span class="co"># specificando anche il nome</span></span>
<span id="cb211-13"><a href="dataframe.html#cb211-13"></a><span class="co">##   Id   Nome Genere Eta    Facolta Media N_esami</span></span>
<span id="cb211-14"><a href="dataframe.html#cb211-14"></a><span class="co">## 1  1  Alice      F  22 Psicologia  27.5      12</span></span>
<span id="cb211-15"><a href="dataframe.html#cb211-15"></a><span class="co">## 2  2  Bruno      M  25 Ingegneria  23.6      14</span></span>
<span id="cb211-16"><a href="dataframe.html#cb211-16"></a><span class="co">## 3  3  Carla      F  23   Medicina  28.3      13</span></span>
<span id="cb211-17"><a href="dataframe.html#cb211-17"></a><span class="co">## 4  4 Davide      M  22    Lettere  29.2      10</span></span>
<span id="cb211-18"><a href="dataframe.html#cb211-18"></a><span class="co">## 5  5  Elisa      F  24 Psicologia  24.8       8</span></span></code></pre></div>
<p>Anche in questo caso sarà necessario che le nuove variabili abbia lo stesso numero di valori delle righe del dataframe.</p>
</div>
<div id="rbind" class="section level4 unnumbered">
<h4><code>rbind()</code></h4>
<p>Leggermente più complessa (e inusuale) è l’aggiunta di righe ad un dataframe. Al contrario della matrice che di base non aveva nomi per le colonne e solo numeri o stringhe come tipologia di dato, per combinare per riga due dataframe dobbiamo avere la stessa struttura. Ovvero:</p>
<ul>
<li>Lo stesso numero di colonne (come per le matrici)</li>
<li>Lo stesso nome delle colonne</li>
</ul>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="dataframe.html#cb212-1"></a>data_short</span>
<span id="cb212-2"><a href="dataframe.html#cb212-2"></a><span class="co">##   Id   Nome Genere Eta    Facolta Media</span></span>
<span id="cb212-3"><a href="dataframe.html#cb212-3"></a><span class="co">## 1  1  Alice      F  22 Psicologia  27.5</span></span>
<span id="cb212-4"><a href="dataframe.html#cb212-4"></a><span class="co">## 2  2  Bruno      M  25 Ingegneria  23.6</span></span>
<span id="cb212-5"><a href="dataframe.html#cb212-5"></a><span class="co">## 3  3  Carla      F  23   Medicina  28.3</span></span>
<span id="cb212-6"><a href="dataframe.html#cb212-6"></a><span class="co">## 4  4 Davide      M  22    Lettere  29.2</span></span>
<span id="cb212-7"><a href="dataframe.html#cb212-7"></a><span class="co">## 5  5  Elisa      F  24 Psicologia  24.8</span></span>
<span id="cb212-8"><a href="dataframe.html#cb212-8"></a></span>
<span id="cb212-9"><a href="dataframe.html#cb212-9"></a><span class="co"># Nuovo dataset con le stesse colonne ma diverso nome</span></span>
<span id="cb212-10"><a href="dataframe.html#cb212-10"></a>new_row &lt;-<span class="st"> </span><span class="kw">data.frame</span>(</span>
<span id="cb212-11"><a href="dataframe.html#cb212-11"></a>  <span class="dt">Id =</span> <span class="dv">6</span>,</span>
<span id="cb212-12"><a href="dataframe.html#cb212-12"></a>  <span class="dt">Nome =</span> <span class="st">&quot;Marta&quot;</span>,</span>
<span id="cb212-13"><a href="dataframe.html#cb212-13"></a>  <span class="dt">Sex =</span> <span class="st">&quot;F&quot;</span>,      <span class="co"># Sex invece di Genere</span></span>
<span id="cb212-14"><a href="dataframe.html#cb212-14"></a>  <span class="dt">Eta =</span> <span class="dv">44</span>,</span>
<span id="cb212-15"><a href="dataframe.html#cb212-15"></a>  <span class="dt">Facolta =</span> <span class="st">&quot;Filosofia&quot;</span>,</span>
<span id="cb212-16"><a href="dataframe.html#cb212-16"></a>  <span class="dt">Media =</span> <span class="fl">28.7</span></span>
<span id="cb212-17"><a href="dataframe.html#cb212-17"></a>)</span>
<span id="cb212-18"><a href="dataframe.html#cb212-18"></a></span>
<span id="cb212-19"><a href="dataframe.html#cb212-19"></a>new_row</span>
<span id="cb212-20"><a href="dataframe.html#cb212-20"></a><span class="co">##   Id  Nome Sex Eta   Facolta Media</span></span>
<span id="cb212-21"><a href="dataframe.html#cb212-21"></a><span class="co">## 1  6 Marta   F  44 Filosofia  28.7</span></span>
<span id="cb212-22"><a href="dataframe.html#cb212-22"></a></span>
<span id="cb212-23"><a href="dataframe.html#cb212-23"></a><span class="kw">rbind</span>(data_short, new_row) <span class="co"># Errore</span></span>
<span id="cb212-24"><a href="dataframe.html#cb212-24"></a><span class="co">## Error in match.names(clabs, names(xi)): names do not match previous names</span></span>
<span id="cb212-25"><a href="dataframe.html#cb212-25"></a></span>
<span id="cb212-26"><a href="dataframe.html#cb212-26"></a><span class="co"># Nuovo dataset con le stesse colonne con il nome corretto</span></span>
<span id="cb212-27"><a href="dataframe.html#cb212-27"></a>new_row &lt;-<span class="st"> </span><span class="kw">data.frame</span>(</span>
<span id="cb212-28"><a href="dataframe.html#cb212-28"></a>  <span class="dt">Id =</span> <span class="dv">6</span>,</span>
<span id="cb212-29"><a href="dataframe.html#cb212-29"></a>  <span class="dt">Nome =</span> <span class="st">&quot;Marta&quot;</span>,</span>
<span id="cb212-30"><a href="dataframe.html#cb212-30"></a>  <span class="dt">Genere =</span> <span class="st">&quot;F&quot;</span>, </span>
<span id="cb212-31"><a href="dataframe.html#cb212-31"></a>  <span class="dt">Eta =</span> <span class="dv">44</span>,</span>
<span id="cb212-32"><a href="dataframe.html#cb212-32"></a>  <span class="dt">Facolta =</span> <span class="st">&quot;Filosofia&quot;</span>,</span>
<span id="cb212-33"><a href="dataframe.html#cb212-33"></a>  <span class="dt">Media =</span> <span class="fl">28.7</span></span>
<span id="cb212-34"><a href="dataframe.html#cb212-34"></a>)</span>
<span id="cb212-35"><a href="dataframe.html#cb212-35"></a></span>
<span id="cb212-36"><a href="dataframe.html#cb212-36"></a><span class="kw">rbind</span>(data_short, new_row)</span>
<span id="cb212-37"><a href="dataframe.html#cb212-37"></a><span class="co">##   Id   Nome Genere Eta    Facolta Media</span></span>
<span id="cb212-38"><a href="dataframe.html#cb212-38"></a><span class="co">## 1  1  Alice      F  22 Psicologia  27.5</span></span>
<span id="cb212-39"><a href="dataframe.html#cb212-39"></a><span class="co">## 2  2  Bruno      M  25 Ingegneria  23.6</span></span>
<span id="cb212-40"><a href="dataframe.html#cb212-40"></a><span class="co">## 3  3  Carla      F  23   Medicina  28.3</span></span>
<span id="cb212-41"><a href="dataframe.html#cb212-41"></a><span class="co">## 4  4 Davide      M  22    Lettere  29.2</span></span>
<span id="cb212-42"><a href="dataframe.html#cb212-42"></a><span class="co">## 5  5  Elisa      F  24 Psicologia  24.8</span></span>
<span id="cb212-43"><a href="dataframe.html#cb212-43"></a><span class="co">## 6  6  Marta      F  44  Filosofia  28.7</span></span></code></pre></div>
<p>Anche in questo caso sarà necessario salvare il risultato ottenuto per mantenere i cambiamenti.</p>
</div>
</div>
<div id="informazioni-dataframe" class="section level3">
<h3><span class="header-section-number">10.3.3</span> Informazioni Dataframe</h3>
<p>Vediamo infine alcune funzioni molto comuni usate per ottenere informazioni riassuntive riguardo ai dati contenuti in un dataframe:</p>
<ul>
<li><code>head()</code> (o <code>tail()</code>) ci permete di visualizzare le prime (o le ulitme righe del nostro dataframe)</li>
</ul>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="dataframe.html#cb213-1"></a><span class="kw">head</span>(my_data)</span>
<span id="cb213-2"><a href="dataframe.html#cb213-2"></a><span class="co">##   Id    names gender age    faculty</span></span>
<span id="cb213-3"><a href="dataframe.html#cb213-3"></a><span class="co">## 1  1    Alice      F  22 Psicologia</span></span>
<span id="cb213-4"><a href="dataframe.html#cb213-4"></a><span class="co">## 2  2    Bruno      M  25 Ingegneria</span></span>
<span id="cb213-5"><a href="dataframe.html#cb213-5"></a><span class="co">## 3  3    Carla      F  23   Medicina</span></span>
<span id="cb213-6"><a href="dataframe.html#cb213-6"></a><span class="co">## 4  4   Davide      M  22    Lettere</span></span>
<span id="cb213-7"><a href="dataframe.html#cb213-7"></a><span class="co">## 5  5    Elisa      F  24 Psicologia</span></span>
<span id="cb213-8"><a href="dataframe.html#cb213-8"></a><span class="co">## 6  6 Fabrizio      M  35    Lettere</span></span></code></pre></div>
<ul>
<li><code>str()</code> ci permete di valutare la struttura del dataset ottenendo utili informazini quali in numero di osservazioni, il numero di variabili e la ipologia di variabili</li>
</ul>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="dataframe.html#cb214-1"></a><span class="kw">str</span>(my_data)</span>
<span id="cb214-2"><a href="dataframe.html#cb214-2"></a><span class="co">## &#39;data.frame&#39;:    10 obs. of  5 variables:</span></span>
<span id="cb214-3"><a href="dataframe.html#cb214-3"></a><span class="co">##  $ Id     : int  1 2 3 4 5 6 7 8 9 10</span></span>
<span id="cb214-4"><a href="dataframe.html#cb214-4"></a><span class="co">##  $ names  : chr  &quot;Alice&quot; &quot;Bruno&quot; &quot;Carla&quot; &quot;Davide&quot; ...</span></span>
<span id="cb214-5"><a href="dataframe.html#cb214-5"></a><span class="co">##  $ gender : Factor w/ 2 levels &quot;F&quot;,&quot;M&quot;: 1 2 1 2 1 2 1 2 1 2</span></span>
<span id="cb214-6"><a href="dataframe.html#cb214-6"></a><span class="co">##  $ age    : num  22 25 23 22 24 35 26 20 23 22</span></span>
<span id="cb214-7"><a href="dataframe.html#cb214-7"></a><span class="co">##  $ faculty: Factor w/ 5 levels &quot;Ingegneria&quot;,&quot;Lettere&quot;,..: 4 1 3 2 4 2 1 4 5 1</span></span></code></pre></div>
<ul>
<li><code>summary()</code> ci permete avere delle informazioni riassuntive delle variabili a seconda della loro tipologia</li>
</ul>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="dataframe.html#cb215-1"></a><span class="kw">summary</span>(my_data)</span>
<span id="cb215-2"><a href="dataframe.html#cb215-2"></a><span class="co">##        Id           names           gender      age              faculty </span></span>
<span id="cb215-3"><a href="dataframe.html#cb215-3"></a><span class="co">##  Min.   : 1.00   Length:10          F:5    Min.   :20.00   Ingegneria:3  </span></span>
<span id="cb215-4"><a href="dataframe.html#cb215-4"></a><span class="co">##  1st Qu.: 3.25   Class :character   M:5    1st Qu.:22.00   Lettere   :2  </span></span>
<span id="cb215-5"><a href="dataframe.html#cb215-5"></a><span class="co">##  Median : 5.50   Mode  :character          Median :23.00   Medicina  :1  </span></span>
<span id="cb215-6"><a href="dataframe.html#cb215-6"></a><span class="co">##  Mean   : 5.50                             Mean   :24.20   Psicologia:3  </span></span>
<span id="cb215-7"><a href="dataframe.html#cb215-7"></a><span class="co">##  3rd Qu.: 7.75                             3rd Qu.:24.75   Statistica:1  </span></span>
<span id="cb215-8"><a href="dataframe.html#cb215-8"></a><span class="co">##  Max.   :10.00                             Max.   :35.00</span></span></code></pre></div>
</div>
<div id="esercizi-11" class="section level3 unnumbered">
<h3>Esercizi</h3>
<p>Facendo riferimento ai dataframe <code>data_long</code> e <code>data_wide</code> (<a href="https://github.com/psicostat/Introduction2R/blob/master/exercises/chapter-10-dataframe.R">soluzioni</a>):</p>
<ol style="list-style-type: decimal">
<li>Aggiungi sia al DataFrame <code>data_wide</code> che <code>data_long</code> la variabile numerica <code>"memory_pre"</code>.</li>
</ol>
<pre><code>##       Id memory_pre
## 1 subj_1          3
## 2 subj_2          2
## 3 subj_3          1</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Aggiungi sia al DataFrame <code>data_wide</code> che <code>data_long</code> la variabile categoriale <code>"gruppo"</code>.</li>
</ol>
<pre><code>##       Id      gruppo
## 1 subj_1 trattamento
## 2 subj_2 trattemento
## 3 subj_3   controllo</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>Aggiungi al DataFrame <code>data_wide</code> i dati del soggetto <code>subj_4</code> e <code>subj_5</code>.</li>
</ol>
<pre><code>##       Id age gender item_1 item_2 item_3 memory_pre      gruppo
## 1 subj_4  25      F      1      0      2          1 trattemento
## 2 subj_5  22      M      1      1      0          3   controllo</code></pre>
<ol start="4" style="list-style-type: decimal">
<li>Considerando il DataFrame <code>datawide</code> calcola la variabile <code>"memory_post"</code> data dalla somma degli item.</li>
<li>Considerando il DataFrame <code>data_wide</code> cambia i nomi delle variabili <code>item_1</code>, <code>item_2</code> e <code>item_3</code> rispettivamente in <code>problem_1</code>, <code>problem_2</code> e <code>problem_3</code>.</li>
</ol>

</div>
</div>
</div>
<hr>
<center>
  <div class="footer">
    Questo libro è rilasciato in accordo con <a href= "https://creativecommons.org/licenses/by-sa/4.0/legalcode">CC BY-SA</a>.
    <br>
    Le illustrazioni utilizzate appartengono a <a href= "https://rstudio4edu.github.io/rstudio4edu-book/">rstudio4edu-book</a> in accordo con <a href= "https://creativecommons.org/licenses/by-nc/2.0/">CC BY-NC</a>.
    <br>
    Per conoscere di più riguardo <span style="color: #8C3031; font-weight:bold"> Psicostat</span> e le nostre attività, visita <a href= "https://psicostat.dpss.psy.unipd.it/">https://psicostat.dpss.psy.unipd.it/</a>.
  </div>
</center>
            </section>

          </div>
        </div>
      </div>
<a href="matrix.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="list.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": true
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/psicostat/Introduction2R/edit/master/12-dataframe.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Introduction2R.pdf", "Introduction2R.epub"],
"toc": {
"collapse": "section",
"scroll_highlight": true,
"toc_float": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
